Repository zitadel/zitadel, pull requests merged in 2020-12, with the labels that each got.

#1019 chore: docker site gen for docs, update npm base image, fix chrome in docs page, jwt profile
  .github/dependabot.yml
  .github/workflows/docs.yml
  .github/workflows/spellcheck.yml
  .typo-ci.yml
  build/.dockerignore
  build/dockerfile
  site/README.md
  site/docker-compose.yml
  site/dockerfile
  site/docs/documentation/03-openidoauth.en.md
  site/package.json
  site/src/components/Docs.svelte
  site/src/components/GuideContents.svelte
  site/src/components/LanguageSwitcher.svelte
  site/src/messages/de.json
  site/src/routes/index.svelte
  site/src/utils/generate_docs.js
  site/static/base.css
Labels: docker, documentation, enhancement

#944 docs: improvement to semantics
  site/docs/administrate/00-overview.en.md
  site/docs/administrate/01-console.en.md
  site/docs/administrate/02-organisations.en.md
  site/docs/administrate/03-projects.en.md
  site/docs/administrate/04-clients.en.md
  site/docs/administrate/05-roles.en.md
  site/docs/administrate/06-users.en.md
  site/docs/administrate/07-policies.en.md
  site/docs/administrate/08-providers.en.md
  site/docs/administrate/09-authorisations.en.md
  site/docs/administrate/09-authorizations.de.md
  site/docs/administrate/09-authorizations.en.md
  site/docs/administrate/09-management-roles.de.md
  site/docs/administrate/09-management-roles.en.md
  site/docs/administrate/70-zitadelroles.en.md
  site/docs/integrate/01-singlepageapp.en.md
  site/docs/integrate/05-proxy.en.md
  site/docs/start/00-quick-start.en.md
  site/static/img/grafana_client_settings.png
  site/static/img/grafana_login_button.png
  site/static/img/grafana_profile_settings.png
  site/static/img/grafana_project_settings.png
  site/static/img/grafana_zitadel_authorization.png
Labels: documentation

#1074 chore(site): dependabot, fix app.render
  site/package-lock.json
  site/package.json
Labels: dependencies, frontend

#1057 fix(operator): migrations
  .gitignore
  migrations/cockroach-secure/V1.0__databases.sql
  migrations/cockroach-secure/V1.11__usermembership.sql
  migrations/cockroach-secure/V1.12__machine_keys.sql
  migrations/cockroach-secure/V1.13__machine_keys_public.sql
  migrations/cockroach-secure/V1.14__auth_loginpolicy.sql
  migrations/cockroach-secure/V1.15__idp_providers.sql
  migrations/cockroach-secure/V1.16__user_session.sql
  migrations/cockroach-secure/V1.17__policies.sql
  migrations/cockroach-secure/V1.18__scope_projectroles.sql
  migrations/cockroach-secure/V1.19__idp_configs.sql
  migrations/cockroach-secure/V1.1__eventstore.sql
  migrations/cockroach-secure/V1.20__label_policies.sql
  migrations/cockroach-secure/V1.21__mfa_policy.sql
  migrations/cockroach-secure/V1.22__user_grant_owners.sql
  migrations/cockroach-secure/V1.2__views.sql
  migrations/cockroach-secure/V1.3__usermembership.sql
  migrations/cockroach-secure/V1.4__compliance.sql
  migrations/cockroach-secure/V1.5__orgdomain_validationtype.sql
  migrations/cockroach-secure/V1.6__origin_allow_list.sql
  migrations/cockroach-secure/V1.7__idps.sql
  migrations/cockroach-secure/V1.8__username_change.sql
  migrations/cockroach-secure/V1.9__token.sql
  migrations/cockroach/V1.0__databases.sql
  migrations/cockroach/V1.10__user_machine.sql
  migrations/cockroach/V1.10__user_machine_keys.sql
  migrations/cockroach/V1.14__auth_loginpolicy.sql
  migrations/cockroach/V1.1__eventstore.sql
  migrations/cockroach/clean_cluster.go
  migrations/cockroach/clean_local.go
  migrations/cockroach/migrate_cluster.go
  migrations/cockroach/migrate_local.go
Labels: bug

#1072 chore(console): dependabot
  console/package-lock.json
  console/package.json
Labels: dependencies, frontend

#1087 chore: Update LICENSE
  LICENSE
Labels: documentation

#1064 fix(console): regex check project app write
  console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
Labels: frontend

#1122 fix: pubsub
  cmd/zitadel/startup.yaml
  internal/admin/repository/eventsourcing/handler/iam_member.go
  internal/admin/repository/eventsourcing/handler/user_external_idps.go
  internal/admin/repository/eventsourcing/view/user.go
  internal/auth/repository/eventsourcing/handler/application.go
  internal/auth/repository/eventsourcing/handler/project_role.go
  internal/auth/repository/eventsourcing/handler/user_membership.go
  internal/auth/repository/eventsourcing/view/application.go
  internal/auth/repository/eventsourcing/view/key.go
  internal/auth/repository/eventsourcing/view/machine_keys.go
  internal/auth/repository/eventsourcing/view/project_role.go
  internal/auth/repository/eventsourcing/view/token.go
  internal/auth/repository/eventsourcing/view/user.go
  internal/auth/repository/eventsourcing/view/user_grant.go
  internal/auth/repository/eventsourcing/view/user_membership.go
  internal/auth/repository/eventsourcing/view/user_session.go
  internal/authz/repository/eventsourcing/view/application.go
  internal/authz/repository/eventsourcing/view/token.go
  internal/authz/repository/eventsourcing/view/user_grant.go
  internal/eventstore/models/object.go
  internal/eventstore/models/search_query_old.go
  internal/eventstore/query/handler.go
  internal/eventstore/spooler/spooler.go
  internal/eventstore/spooler/spooler_test.go
  internal/management/repository/eventsourcing/eventstore/user.go
  internal/management/repository/eventsourcing/handler/project_grant.go
  internal/management/repository/eventsourcing/handler/project_grant_member.go
  internal/management/repository/eventsourcing/handler/user.go
  internal/management/repository/eventsourcing/handler/user_grant.go
  internal/management/repository/eventsourcing/handler/user_membership.go
  internal/management/repository/eventsourcing/view/application.go
  internal/management/repository/eventsourcing/view/machine_keys.go
  internal/management/repository/eventsourcing/view/org_domain.go
  internal/management/repository/eventsourcing/view/org_member.go
  internal/management/repository/eventsourcing/view/project.go
  internal/management/repository/eventsourcing/view/project_grant_member.go
  internal/management/repository/eventsourcing/view/project_member.go
  internal/management/repository/eventsourcing/view/project_role.go
  internal/management/repository/eventsourcing/view/user.go
  internal/management/repository/eventsourcing/view/user_grant.go
  internal/management/repository/eventsourcing/view/user_membership.go
  internal/notification/repository/eventsourcing/handler/notification.go
  internal/notification/repository/eventsourcing/view/notify_user.go
  internal/notification/templates/templateData.go
  internal/org/repository/eventsourcing/eventstore_mock_test.go
  internal/org/repository/eventsourcing/eventstore_test.go
  internal/project/repository/view/application_view.go
  internal/project/repository/view/project_role_view.go
  internal/user/repository/eventsourcing/eventstore.go
Labels: api, backend, bug, enhancement, eventstore, go
