Repository zitadel/zitadel, pull requests merged in 2020-05, with the labels that each got.

#80 chore: remove not existing upstream
  go.mod
Labels: dependencies

#84 chore: add correct upstream
  go.mod
Labels: dependencies

#106 chore: matrix build
  .github/workflows/release.yml
  .releaserc.js
  build/docker/prod
Labels: enhancement

#144 fix(console): npm, update karma, protractor
  console/package-lock.json
  console/package.json
Labels: dependencies, javascript

#146 chore: deployment manifest, kaniko
  k8s/base/deployment.yaml
  k8s/base/flow.yaml
  k8s/base/kustomization.yaml
  k8s/base/output.yaml
  k8s/base/service-accounts.yaml
  k8s/base/service-api-admin.yaml
  k8s/base/service-api-auth.yaml
  k8s/base/service-api-mangagement.yaml
  k8s/base/service-console.yaml
Labels: documentation, enhancement
