Repository zitadel/zitadel, pull requests merged in 2020-06, with the labels that each got.

#229 feat(console): profile initializers, contributors for grants
  console/src/app/pages/orgs/orgs.module.ts
  console/src/app/pages/project-role-create/project-role-create.component.html
  console/src/app/pages/project-role-create/project-role-create.component.ts
  console/src/app/pages/projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/project-contributors/project-contributors.component.html
  console/src/app/pages/projects/project-contributors/project-contributors.component.scss
  console/src/app/pages/projects/project-contributors/project-contributors.component.spec.ts
  console/src/app/pages/projects/project-contributors/project-contributors.component.ts
  console/src/app/pages/projects/projects.module.ts
  console/src/app/pages/user-create/user-create.component.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.ts
  console/src/app/pages/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/user-detail/user-detail/user-detail.component.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: enhancement

#233 feat(console): getuserbyid, fix password policy validation, read iam
  console/src/app/pages/apps/app-detail/app-detail.component.html
  console/src/app/pages/apps/app-detail/app-detail.component.scss
  console/src/app/pages/apps/app-detail/app-detail.component.ts
  console/src/app/pages/orgs/org-create/org-create.component.html
  console/src/app/pages/orgs/org-create/org-create.component.ts
  console/src/app/pages/orgs/org-create/org-create.module.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/granted-project-detail/granted-project-detail.component.scss
  console/src/app/pages/projects/granted-project-detail/granted-project-detail.component.ts
  console/src/app/pages/projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-project-detail/owned-project-detail.component.scss
  console/src/app/pages/projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/user-create/user-create.component.html
  console/src/app/pages/user-create/user-create.component.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.ts
  console/src/app/pages/user-detail/detail-form/detail-form.component.html
  console/src/app/pages/user-detail/detail-form/detail-form.component.ts
  console/src/app/pages/user-detail/user-detail.module.ts
  console/src/app/pages/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/user-detail/user-detail/user-detail.component.ts
  console/src/app/pipes/password-pattern.pipe.spec.ts
  console/src/app/pipes/password-pattern.pipe.ts
  console/src/app/pipes/pipes.module.ts
  console/src/app/proto/generated/admin_grpc_web_pb.d.ts
  console/src/app/proto/generated/admin_grpc_web_pb.js
  console/src/app/proto/generated/admin_pb.d.ts
  console/src/app/proto/generated/admin_pb.js
  console/src/app/proto/generated/auth_grpc_web_pb.d.ts
  console/src/app/proto/generated/auth_grpc_web_pb.js
  console/src/app/proto/generated/auth_pb.d.ts
  console/src/app/proto/generated/auth_pb.js
  console/src/app/proto/generated/management_grpc_web_pb.d.ts
  console/src/app/proto/generated/management_grpc_web_pb.js
  console/src/app/proto/generated/management_pb.d.ts
  console/src/app/proto/generated/management_pb.js
  console/src/app/services/auth-user.service.ts
  console/src/app/services/mgmt-user.service.ts
  console/src/app/services/org.service.ts
  console/src/app/services/project.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: bug, enhancement

#235 feat(console): add and remove org domains, show userLoginNames
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.scss
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/org-members/org-members.component.ts
  console/src/app/pages/projects/project-contributors/project-contributors.component.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.ts
  console/src/app/pages/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/user-detail/user-detail/user-detail.component.scss
  console/src/app/pages/user-detail/user-detail/user-detail.component.ts
  console/src/app/proto/generated/auth_grpc_web_pb.d.ts
  console/src/app/proto/generated/auth_grpc_web_pb.js
  console/src/app/proto/generated/auth_pb.d.ts
  console/src/app/proto/generated/auth_pb.js
  console/src/app/proto/generated/management_pb.js
  console/src/app/services/mgmt-user.service.ts
  console/src/app/services/org.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: enhancement

#224 chore(semrel): use bot to check messages for compliance
  .github/semantic.yml
Labels: documentation

#244 chore(dependabot): docker scan
  .github/dependabot.yml
Labels: dependencies
