Repository zitadel/zitadel, pull requests merged in 2020-10, with the labels that each got.

#691 fix(container): stop copying / and instead only copy zitadel
  .github/workflows/docs.yml
  .github/workflows/release.yml
  build/docker/Dockerfile
Labels: dependencies, enhancement

#817 fix(console): policies frontend
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.html
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.html
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.ts
  console/src/app/modules/policies/password-iam-policy/password-iam-policy.component.html
  console/src/app/modules/policies/password-iam-policy/password-iam-policy.component.ts
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.html
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.ts
  console/src/app/pages/orgs/org-create/org-create.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/orgs-routing.module.ts
  console/src/app/pages/orgs/policy-grid/policy-grid.component.html
  console/src/app/pages/orgs/policy-grid/policy-grid.component.ts
  console/src/app/services/admin.service.ts
  console/src/app/services/mgmt.service.ts
Labels: frontend

#819 feat(console): delete user
  console/src/app/modules/warn-dialog/warn-dialog.component.html
  console/src/app/pages/iam/iam-views/iam-views.component.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.scss
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
  console/src/app/pages/users/user-list/user-list.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.scss
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#820 fix(console): intercept navigator.language, set browser lang as default for user without explicit setting, user table outline, member create dialog import
  console/src/app/app.component.ts
  console/src/app/app.module.ts
  console/src/app/modules/add-member-dialog/member-create-dialog.module.ts
  console/src/app/modules/idp-table/idp-table.component.html
  console/src/app/modules/project-members/project-members.module.ts
  console/src/app/pages/iam/iam-members/iam-members.module.ts
  console/src/app/pages/orgs/org-members/org-members.module.ts
  console/src/app/pages/orgs/orgs.module.ts
  console/src/app/pages/users/user-detail/external-idps/external-idps.component.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.scss
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/app/services/grpc.service.ts
  console/src/app/services/interceptors/i18n.interceptor.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#821 fix(console): permission regex, account switcher null check, restrict app and member create access
  console/src/app/app.component.html
  console/src/app/modules/accounts-card/accounts-card.component.ts
  console/src/app/modules/add-member-dialog/member-create-dialog.component.html
  console/src/app/modules/add-member-dialog/member-create-dialog.component.ts
  console/src/app/modules/members-table/members-table.component.html
  console/src/app/modules/members-table/members-table.component.ts
  console/src/app/modules/policies/login-policy/login-policy.component.html
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.html
  console/src/app/modules/project-members/project-members.component.html
  console/src/app/modules/project-roles/project-roles.component.html
  console/src/app/pages/iam/iam-members/iam-members.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-members/org-members.component.html
  console/src/app/pages/orgs/policy-grid/policy-grid.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.scss
  console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/project-grants/project-grants.component.html
  console/src/app/pages/users/user-detail/memberships/memberships.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-list/user-list.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.html
Labels: frontend

#824 feat(console): policy settings for iam and org
  console/src/app/modules/accounts-card/accounts-card.component.scss
  console/src/app/modules/detail-layout/detail-layout.component.scss
  console/src/app/modules/idp-table/idp-table.component.html
  console/src/app/modules/policies/login-policy/login-policy.component.html
  console/src/app/modules/policies/login-policy/login-policy.component.scss
  console/src/app/modules/policies/login-policy/login-policy.component.ts
  console/src/app/modules/policies/password-age-policy/password-age-policy-routing.module.ts
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.html
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.scss
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy-routing.module.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.html
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.scss
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.ts
  console/src/app/modules/policies/password-iam-policy/password-iam-policy-routing.module.ts
  console/src/app/modules/policies/password-iam-policy/password-iam-policy.component.html
  console/src/app/modules/policies/password-iam-policy/password-iam-policy.component.scss
  console/src/app/modules/policies/password-iam-policy/password-iam-policy.component.ts
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy-routing.module.ts
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.html
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.scss
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.ts
  console/src/app/modules/policies/policy-component-action.enum.ts
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.html
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.ts
  console/src/app/pages/iam/iam-routing.module.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/orgs-routing.module.ts
  console/src/app/pages/orgs/policy-grid/policy-grid.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.scss
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.ts
  console/src/app/pages/projects/owned-projects/owned-projects.module.ts
  console/src/app/services/admin.service.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/environment.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: javascript

#835 feat(console): delete external idp from user
  console/src/app/pages/users/user-detail/external-idps/external-idps.component.html
  console/src/app/pages/users/user-detail/external-idps/external-idps.component.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#844 feat(console): seo metatags, fix policy bugs, project options
  console/src/app/app.module.ts
  console/src/app/modules/idp-table/idp-table.component.ts
  console/src/app/modules/policies/login-policy/login-policy.component.html
  console/src/app/modules/policies/login-policy/login-policy.component.scss
  console/src/app/modules/policies/login-policy/login-policy.component.ts
  console/src/app/modules/policies/login-policy/login-policy.module.ts
  console/src/app/modules/policies/org-iam-policy/org-iam-policy.component.ts
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.html
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.html
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.scss
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.module.ts
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.html
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.ts
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.ts
  console/src/app/pages/iam/iam.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.scss
  console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.scss
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/users/user-detail/external-idps/external-idps.component.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/services/mgmt.service.ts
  console/src/app/services/seo.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/index.html
Labels: frontend

#870 fix(console): idp create, table, i18n
  console/src/app/modules/idp-create/idp-create.component.html
  console/src/app/modules/idp-create/idp-create.component.ts
  console/src/app/modules/idp-create/idp-create.module.ts
  console/src/app/modules/idp-table/idp-table.component.html
  console/src/app/modules/idp-table/idp-table.component.scss
  console/src/app/modules/idp-table/idp-table.component.ts
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.html
  console/src/app/pages/orgs/orgs-routing.module.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#875 fix(console): login policy, idp type filter
  console/src/app/app.component.scss
  console/src/app/modules/detail-layout/detail-layout.component.html
  console/src/app/modules/detail-layout/detail-layout.component.scss
  console/src/app/modules/idp-table/idp-table.component.scss
  console/src/app/modules/idp/idp.component.html
  console/src/app/modules/idp/idp.component.ts
  console/src/app/modules/policies/login-policy/add-idp-dialog/add-idp-dialog.component.html
  console/src/app/modules/policies/login-policy/add-idp-dialog/add-idp-dialog.component.ts
  console/src/app/modules/policies/login-policy/login-policy.component.html
  console/src/app/modules/policies/login-policy/login-policy.component.scss
  console/src/app/modules/policies/login-policy/login-policy.component.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#876 fix(console): user autocomplete emitter
  console/src/app/modules/search-user-autocomplete/search-user-autocomplete.component.ts
Labels: frontend

#883 fix(console): idp style field, idp redirect, table
  console/src/app/modules/idp-table/idp-table.component.scss
  console/src/app/modules/idp-table/idp-table.component.ts
  console/src/app/modules/idp/idp.component.html
  console/src/app/modules/idp/idp.component.ts
Labels: frontend

#836 fix(console): clear storage entry if org is unknown, use zitadel as storage prefix, prettier domain verification
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.html
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-projects.component.ts
  console/src/app/services/interceptors/org.interceptor.ts
  console/src/app/services/storage.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/images/zitadel-social-preview25.png
  console/src/index.html
Labels: frontend

#864 feat(docs): quickstart, clients and projects
  site/docs/administrate/02-organisations.en.md
  site/docs/administrate/03-projects.en.md
  site/docs/administrate/04-clients.en.md
  site/docs/administrate/06-users.en.md
  site/docs/start/00-quick-start.en.md
  site/docs/use/00-user.en.md
  site/static/img/accounts_org_register.png
  site/static/img/accounts_otp_select.png
  site/static/img/accounts_otp_setup.png
  site/static/img/accounts_otp_setup_done.png
  site/static/img/accounts_otp_verify.png
  site/static/img/accounts_page.png
  site/static/img/accounts_password.png
  site/static/img/accounts_verify_code_password.png
  site/static/img/accounts_verify_code_password_done.png
  site/static/img/console_clients_my_first_spa_config.png
  site/static/img/console_clients_my_first_spa_wizard_1.png
  site/static/img/console_clients_my_first_spa_wizard_2.png
  site/static/img/console_clients_my_first_spa_wizard_3.png
  site/static/img/console_clients_my_first_spa_wizard_4.png
  site/static/img/console_org_domain.png
  site/static/img/console_org_domain_add.png
  site/static/img/console_org_domain_added.png
  site/static/img/console_org_domain_default.png
  site/static/img/console_org_domain_primary.png
  site/static/img/console_org_domain_verified.png
  site/static/img/console_org_domain_verify.png
  site/static/img/console_org_domain_verify_dns.png
  site/static/img/console_personal_information.png
  site/static/img/console_personal_information_org_owner.png
  site/static/img/console_projects_empty.png
  site/static/img/console_projects_my_first_project.png
  site/static/img/console_user_create_done.png
  site/static/img/console_user_create_form.png
  site/static/img/console_user_list.png
  site/static/img/console_user_list_search.png
  site/static/img/console_user_personal_info.png
Labels: documentation, enhancement

#896 fix: update oidc pkg for basic auth
  go.mod
  go.sum
Labels: backend, bug, go

#890 feat(console): email label policy, cleanup policy grid module
  console/src/app/modules/detail-layout/detail-layout.component.scss
  console/src/app/modules/policies/label-policy/label-policy-routing.module.ts
  console/src/app/modules/policies/label-policy/label-policy.component.html
  console/src/app/modules/policies/label-policy/label-policy.component.scss
  console/src/app/modules/policies/label-policy/label-policy.component.spec.ts
  console/src/app/modules/policies/label-policy/label-policy.component.ts
  console/src/app/modules/policies/label-policy/label-policy.module.ts
  console/src/app/modules/policies/login-policy/login-policy.component.html
  console/src/app/modules/policies/login-policy/login-policy.component.ts
  console/src/app/modules/policies/org-iam-policy/org-iam-policy.component.html
  console/src/app/modules/policies/org-iam-policy/org-iam-policy.component.ts
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.html
  console/src/app/modules/policies/password-age-policy/password-age-policy.component.ts
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.html
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.ts
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.html
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.ts
  console/src/app/modules/policies/policy-component-types.enum.ts
  console/src/app/modules/policy-grid/policy-grid.component.html
  console/src/app/modules/policy-grid/policy-grid.component.scss
  console/src/app/modules/policy-grid/policy-grid.component.spec.ts
  console/src/app/modules/policy-grid/policy-grid.component.ts
  console/src/app/modules/policy-grid/policy-grid.module.ts
  console/src/app/pages/iam/failed-events/failed-events.component.html
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.html
  console/src/app/pages/iam/iam-policy-grid/iam-policy-grid.component.ts
  console/src/app/pages/iam/iam-routing.module.ts
  console/src/app/pages/iam/iam.component.html
  console/src/app/pages/iam/iam.component.ts
  console/src/app/pages/iam/iam.module.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/orgs.module.ts
  console/src/app/pages/orgs/policy-grid/policy-grid.component.html
  console/src/app/pages/orgs/policy-grid/policy-grid.component.scss
  console/src/app/pages/orgs/policy-grid/policy-grid.component.ts
  console/src/app/services/admin.service.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: enhancement, frontend, javascript

#905 docs: image gallery viewer
  site/docs/administrate/02-organisations.en.md
  site/docs/administrate/03-projects.en.md
  site/docs/administrate/04-clients.en.md
  site/docs/administrate/06-users.en.md
  site/docs/develop/00-overview.en.md
  site/docs/documentation/03-openidoauth.en.md
  site/docs/integrate/01-openidoauth.en.md
  site/docs/start/00-quick-start.en.md
  site/docs/use/00-user.en.md
  site/package-lock.json
  site/package.json
  site/rollup.config.js
  site/src/client.js
  site/src/components/PhotoSwipe.svelte
  site/src/routes/[slug].svelte
  site/src/routes/_layout.svelte
  site/src/template.html
  site/src/utils/photoswipe.js
  site/static/base.css
  site/static/default-skin/default-skin.css
  site/static/default-skin/default-skin.png
  site/static/default-skin/default-skin.svg
  site/static/default-skin/preloader.gif
  site/static/img/accounts_org_register.png
  site/static/photoswipe-ui-default.min.js
  site/static/photoswipe.css
  site/static/photoswipe.min.js
  site/static/prism.css
Labels: documentation, frontend, javascript

#889 chore: spell check automation and spellcheck
  .github/workflows/spellcheck.yml
  .typo-ci.yml
  site/README.md
  site/docs/administrate/01-console.en.md
  site/docs/administrate/02-organisations.en.md
  site/docs/administrate/03-projects.en.md
  site/docs/administrate/04-clients.en.md
  site/docs/administrate/05-roles.en.md
  site/docs/administrate/06-users.en.md
  site/docs/administrate/07-policies.en.md
  site/docs/administrate/08-providers.en.md
  site/docs/administrate/90-system.en.md
  site/docs/develop/00-overview.en.md
  site/docs/develop/02-management.en.md
  site/docs/documentation/01-priciples.en.md
  site/docs/documentation/03-openidoauth.en.md
  site/docs/start/00-quick-start.en.md
Labels: documentation, enhancement

#907 fix(console): start verification flow on domain create, show verification if token is requested
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.html
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.scss
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/assets/i18n/de.json
Labels: enhancement, frontend, javascript

#912 docs: screenshots and text improvements
  site/docs/administrate/01-console.en.md
  site/docs/administrate/02-organisations.en.md
  site/docs/administrate/03-projects.en.md
  site/docs/administrate/06-users.en.md
  site/docs/administrate/09-authorisations.de.md
  site/docs/administrate/09-authorisations.en.md
  site/docs/administrate/70-zitadelroles.de.md
  site/docs/administrate/70-zitadelroles.en.md
  site/docs/administrate/90-system.en.md
  site/docs/documentation/02-architecture.en.md
  site/docs/use/00-user.en.md
  site/static/img/console_admin_entry.png
  site/static/img/console_admin_system.png
  site/static/img/console_authz_add_1.png
  site/static/img/console_authz_add_2.png
  site/static/img/console_authz_add_3.png
  site/static/img/console_authz_overview.png
  site/static/img/console_iam_admin_failed.png
  site/static/img/console_iam_admin_views.png
  site/static/img/console_org_manage_roles_1.png
  site/static/img/console_org_manage_roles_2.png
  site/static/img/console_project_manage_roles_1.png
  site/static/img/console_project_manage_roles_2.png
  site/static/img/console_user_entry.png
  site/static/img/console_user_manage_roles_1.png
  site/static/img/console_user_manage_roles_2.png
  site/static/img/console_user_personal_information.png
  site/static/img/zitadel_cluster_architecture.png
  site/static/img/zitadel_multicluster_architecture.png
  site/static/img/zitadel_software_architecture.png
Labels: documentation, enhancement
