Repository zitadel/zitadel, pull requests merged in 2020-09, with the labels that each got.

#658 fix(console): partial authconfig prompt, regex permissions
  console/src/app/modules/user-grants/user-grants.component.ts
  console/src/app/pages/iam/iam-members/iam-members.component.html
  console/src/app/pages/orgs/org-members/org-members.component.html
  console/src/app/pages/orgs/org-members/org-members.component.ts
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.html
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-detail.component.html
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-detail.component.ts
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-detail.module.ts
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-members/project-grant-members.component.html
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-members/project-grant-members.component.ts
  console/src/app/pages/projects/owned-projects/project-grant-detail/project-grant-members/project-grant-members.module.ts
  console/src/app/pages/projects/project-grant-create/project-grant-create.component.ts
  console/src/app/pages/users/user-detail/detail-form/detail-form.component.html
  console/src/app/pages/users/user-detail/detail-form/detail-form.component.ts
  console/src/app/pages/users/user-detail/memberships/memberships.component.html
  console/src/app/pages/users/user-detail/memberships/memberships.component.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.scss
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
  console/src/app/pages/users/user-list/user-list.component.html
  console/src/app/pages/users/user-list/user-list.module.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/app/services/grpc.service.ts
  console/src/app/services/mgmt.service.ts
Labels: frontend

#688 feat(console): set primary domain, fix org create permission
  console/src/app/app-routing.module.ts
  console/src/app/app.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.scss
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/services/grpc-auth.service.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#716 fix(console): show machine key after creation, fix bulk delete
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.html
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.ts
  console/src/app/pages/users/user-detail/machine-keys/show-key-dialog/show-key-dialog.component.html
  console/src/app/pages/users/user-detail/machine-keys/show-key-dialog/show-key-dialog.component.scss
  console/src/app/pages/users/user-detail/machine-keys/show-key-dialog/show-key-dialog.component.spec.ts
  console/src/app/pages/users/user-detail/machine-keys/show-key-dialog/show-key-dialog.component.ts
  console/src/app/pages/users/user-detail/machine-keys/show-key-dialog/show-key-dialog.module.ts
  console/src/app/pages/users/user-detail/user-detail.module.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#725 fix(console): enable phonenumber edit
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: bug, frontend

#729 fix(console): otp delete comfirmation
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts
  console/src/app/pages/users/user-detail/user-detail.module.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#711 fix(docs): path to edit in github
  site/src/components/Docs.svelte
Labels: documentation, frontend

#728 feat(console): refresh roles, user-grants and project-members based on previous navigation
  console/src/app/app.module.ts
  console/src/app/modules/project-members/project-members.component.ts
  console/src/app/modules/project-roles/project-roles.component.html
  console/src/app/modules/refresh-table/refresh-table.component.ts
  console/src/app/modules/user-grants/user-grants.component.html
  console/src/app/modules/user-grants/user-grants.component.ts
  console/src/app/pages/iam/iam-members/iam-members.component.ts
  console/src/app/pages/iam/iam.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/org-members/org-members.component.ts
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/project-grants/project-grants.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/project-grants/project-grants.component.ts
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.ts
  console/src/app/pages/users/user-detail/membership-detail/membership-detail.component.ts
  console/src/app/pages/users/user-detail/memberships/memberships.component.html
  console/src/app/pages/users/user-detail/memberships/memberships.component.scss
  console/src/app/pages/users/user-detail/memberships/memberships.component.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/app/services/refresh.service.ts
Labels: frontend

#745 fix(translations): improved translations
  SECURITY.md
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#794 fix(console): search project regexp
  console/src/app/app.component.ts
Labels: frontend
