Repository zitadel/zitadel, pull requests merged in 2020-11, with the labels that each got.

#911 docs: searchable documentation & seo
  site/docs/administrate/seo_de.html
  site/docs/administrate/seo_en.html
  site/package-lock.json
  site/package.json
  site/src/components/Button.svelte
  site/src/components/Docs.svelte
  site/src/components/DocsHeader.svelte
  site/src/components/GuideContents.svelte
  site/src/components/Icon.svelte
  site/src/components/LanguageSwitcher.svelte
  site/src/components/Nav.svelte
  site/src/components/NavItem.svelte
  site/src/components/SearchSelector.svelte
  site/src/components/SearchTrigger.svelte
  site/src/messages/de.json
  site/src/messages/en.json
  site/src/routes/[slug].json.js
  site/src/routes/[slug].svelte
  site/src/routes/_layout.svelte
  site/src/routes/index.svelte
  site/src/utils/generate_docs.js
  site/src/utils/generate_seo.js
  site/static/base.css
  site/static/icons/android-chrome-192x192.png
  site/static/icons/android-chrome-512x512.png
  site/static/icons/apple-touch-icon.png
  site/static/icons/favicon-16x16.png
  site/static/icons/favicon-32x32.png
  site/static/icons/favicon.ico
  site/static/icons/mstile-150x150.png
  site/static/icons/safari-pinned-tab.svg
  site/static/img/develop2.png
  site/static/img/personal2.png
  site/static/img/projects2.png
  site/static/img/usermanual.png
Labels: documentation, frontend

#942 chore(translation): suggest different translations
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: enhancement, frontend

#951 docs(site): i18n handler, prettier code blocks and highlighting
  site/docs/integrate/01-singlepageapp.en.md
  site/src/components/LanguageSwitcher.svelte
  site/src/i18n.js
  site/src/routes/_layout.svelte
  site/src/routes/index.svelte
  site/src/template.html
  site/static/base.css
  site/static/prism.css
Labels: documentation, frontend

#916 feat(console): user grant filtering, org domain verification improvements, fix membership detail link
  console/src/app/app.component.html
  console/src/app/app.component.scss
  console/src/app/app.component.ts
  console/src/app/modules/card/card.component.scss
  console/src/app/modules/card/card.scss
  console/src/app/modules/changes/changes.component.scss
  console/src/app/modules/meta-layout/meta-layout.component.scss
  console/src/app/modules/meta-layout/meta.scss
  console/src/app/modules/policies/login-policy/login-policy.component.scss
  console/src/app/modules/policies/org-iam-policy/org-iam-policy.component.scss
  console/src/app/modules/policies/password-complexity-policy/password-complexity-policy.component.scss
  console/src/app/modules/policies/password-lockout-policy/password-lockout-policy.component.scss
  console/src/app/modules/policy-grid/policy-grid.component.scss
  console/src/app/modules/user-grants/user-grants-datasource.ts
  console/src/app/modules/user-grants/user-grants.component.html
  console/src/app/modules/user-grants/user-grants.component.scss
  console/src/app/modules/user-grants/user-grants.component.ts
  console/src/app/modules/user-grants/user-grants.module.ts
  console/src/app/pages/home/home.component.html
  console/src/app/pages/home/home.component.scss
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.html
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.scss
  console/src/app/pages/orgs/org-detail/domain-verification/domain-verification.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.scss
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/orgs.module.ts
  console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-grid/granted-project-grid.component.html
  console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-grid/granted-project-grid.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.ts
  console/src/app/pages/users/user-create/user-create.component.ts
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.scss
  console/src/app/pages/users/user-detail/memberships/memberships.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.scss
  console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.scss
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.scss
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/component-themes.scss
  console/src/styles.scss
  console/src/styles/link.scss
  console/src/styles/sidenav-list.scss
  console/src/styles/table.scss
Labels: frontend

#980 chore: docker compose path
  build/README.md
Labels: documentation

#981 chore: contribution link
  README.md
Labels: documentation

#1021 fix(console): sidenav ordering and naming, split eventstore to its own view, documentation link in header
  console/src/app/app.component.html
  console/src/app/app.component.scss
  console/src/app/pages/iam/eventstore/eventstore.component.html
  console/src/app/pages/iam/eventstore/eventstore.component.scss
  console/src/app/pages/iam/eventstore/eventstore.component.spec.ts
  console/src/app/pages/iam/eventstore/eventstore.component.ts
  console/src/app/pages/iam/iam-routing.module.ts
  console/src/app/pages/iam/iam.component.html
  console/src/app/pages/iam/iam.module.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/styles.scss
  console/src/styles/sidenav-list.scss
Labels: frontend

#954 docs(oauth2): jwt profile
  site/docs/documentation/03-openidoauth.en.md
  site/src/messages/de.json
Labels: documentation

#1023 fix(spooler): fast start
  internal/eventstore/spooler/spooler.go
Labels: backend, documentation, enhancement, go

#1025 fix(console): add resource id to meta layout, error highlighting formfield label, missing tooltips, cleanup app detail
  console/src/app/app.component.html
  console/src/app/app.component.scss
  console/src/app/modules/accounts-card/accounts-card.component.scss
  console/src/app/modules/contributors/contributors.component.html
  console/src/app/modules/form-field/form-field.component.ts
  console/src/app/modules/info-section/info-section.component.html
  console/src/app/modules/info-section/info-section.component.scss
  console/src/app/modules/info-section/info-section.component.spec.ts
  console/src/app/modules/info-section/info-section.component.ts
  console/src/app/modules/info-section/info-section.module.ts
  console/src/app/modules/label/label.component.scss
  console/src/app/modules/meta-layout/meta.scss
  console/src/app/pages/iam/iam.component.html
  console/src/app/pages/iam/iam.component.scss
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.scss
  console/src/app/pages/projects/apps/app-detail/app-detail.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.scss
  console/src/app/pages/projects/apps/apps.module.ts
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.scss
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.scss
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.scss
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.scss
  console/src/app/pages/users/user-detail/external-idps/external-idps.component.html
  console/src/app/pages/users/user-detail/memberships/memberships.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.scss
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/component-themes.scss
  console/src/styles/error.scss
  console/src/styles/input.scss
Labels: enhancement, frontend, javascript
