Repository zitadel/zitadel, pull requests merged in 2020-07, with the labels that each got.

#324 fix(management): map all fields in user grant view converter
  internal/management/repository/eventsourcing/handler/user_grant.go
  internal/usergrant/model/user_grant_view.go
  internal/usergrant/repository/view/model/user_grant.go
  migrations/cockroach/V1.25__management_user_grant.sql
  pkg/management/api/grpc/management.pb.go
  pkg/management/api/grpc/management.pb.gw.go
  pkg/management/api/grpc/management.swagger.json
  pkg/management/api/grpc/user_grant_converter.go
  pkg/management/api/proto/management.proto
Labels: bug

#340 feat(console): bump dependencies
  console/package-lock.json
  console/package.json
  console/tsconfig.base.json
Labels: frontend

#341 fix(console): application state, add project role bulk, user grant explanations, i18n, ngsw update prompt
  console/src/app/app.component.html
  console/src/app/pages/apps/app-detail/app-detail.component.ts
  console/src/app/pages/project-grant-create/project-grant-create.component.html
  console/src/app/pages/project-role-create/project-role-create.component.ts
  console/src/app/pages/user-grant-create/user-grant-create.component.html
  console/src/app/services/project.service.ts
  console/src/app/services/update.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#356 fix(postgres): no password in connection string when empty
  internal/config/types/sql.go
Labels: bug, go

#357 fix(console): ui/ux improvements, delete user phone, pinned cards, user grant role load fix
  console/src/app/app.component.html
  console/src/app/app.component.scss
  console/src/app/modules/user-grants/user-grants.component.html
  console/src/app/modules/user-grants/user-grants.component.ts
  console/src/app/pages/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/granted-projects/granted-project-grid/granted-project-grid.component.html
  console/src/app/pages/granted-projects/granted-project-grid/granted-project-grid.component.scss
  console/src/app/pages/granted-projects/granted-project-grid/granted-project-grid.component.ts
  console/src/app/pages/granted-projects/granted-project-list/granted-project-list.component.html
  console/src/app/pages/granted-projects/granted-project-list/granted-project-list.component.ts
  console/src/app/pages/granted-projects/granted-projects.component.ts
  console/src/app/pages/granted-projects/granted-projects.module.ts
  console/src/app/pages/orgs/org-create/org-create.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/owned-projects/owned-project-detail/owned-project-detail.component.scss
  console/src/app/pages/owned-projects/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/owned-projects/owned-project-grid/owned-project-grid.component.scss
  console/src/app/pages/owned-projects/owned-project-grid/owned-project-grid.component.ts
  console/src/app/pages/owned-projects/owned-project-list/owned-project-list.component.ts
  console/src/app/pages/owned-projects/owned-projects.component.ts
  console/src/app/pages/owned-projects/owned-projects.module.ts
  console/src/app/pages/owned-projects/project-grants/project-grants.component.html
  console/src/app/pages/owned-projects/project-grants/project-grants.component.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/user-detail/auth-user-detail/auth-user-detail.component.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.html
  console/src/app/pages/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.scss
  console/src/app/pages/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.spec.ts
  console/src/app/pages/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts
  console/src/app/pages/user-detail/auth-user-detail/code-dialog/code-dialog.component.html
  console/src/app/pages/user-detail/auth-user-detail/code-dialog/code-dialog.component.scss
  console/src/app/pages/user-detail/auth-user-detail/code-dialog/code-dialog.component.spec.ts
  console/src/app/pages/user-detail/auth-user-detail/code-dialog/code-dialog.component.ts
  console/src/app/pages/user-detail/auth-user-detail/dialog-otp/dialog-otp.component.html
  console/src/app/pages/user-detail/auth-user-detail/dialog-otp/dialog-otp.component.scss
  console/src/app/pages/user-detail/auth-user-detail/dialog-otp/dialog-otp.component.ts
  console/src/app/pages/user-detail/code-dialog/code-dialog.module.ts
  console/src/app/pages/user-detail/password/password.component.spec.ts
  console/src/app/pages/user-detail/user-detail.module.ts
  console/src/app/pages/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/user-detail/user-detail/user-detail.component.scss
  console/src/app/pages/user-detail/user-detail/user-detail.component.ts
  console/src/app/pages/user-detail/user-mfa/user-mfa.component.html
  console/src/app/proto/generated/auth_grpc_web_pb.d.ts
  console/src/app/proto/generated/auth_grpc_web_pb.js
  console/src/app/proto/generated/auth_pb.d.ts
  console/src/app/proto/generated/auth_pb.js
  console/src/app/proto/generated/management_grpc_web_pb.d.ts
  console/src/app/proto/generated/management_grpc_web_pb.js
  console/src/app/services/auth-user.service.ts
  console/src/app/services/mgmt-user.service.ts
  console/src/app/services/storage.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/styles/table.scss
Labels: frontend

#266 chore(console): gen proto on npm postinstall, ignore generated output
  .github/workflows/release.yml
  .gitignore
  build/console/generate-grpc.sh
  console/.gitignore
  console/package.json
  console/src/app/proto/generated/auth_grpc_web_pb.d.ts
  console/src/app/proto/generated/auth_grpc_web_pb.js
  console/src/app/proto/generated/auth_pb.d.ts
  console/src/app/proto/generated/auth_pb.js
  console/src/app/proto/generated/authoption/options_pb.d.ts
  console/src/app/proto/generated/authoption/options_pb.js
  console/src/app/proto/generated/google/api/annotations_pb.d.ts
  console/src/app/proto/generated/google/api/annotations_pb.js
  console/src/app/proto/generated/management_grpc_web_pb.d.ts
  console/src/app/proto/generated/management_grpc_web_pb.js
  console/src/app/proto/generated/management_pb.d.ts
  console/src/app/proto/generated/management_pb.js
  console/src/app/proto/generated/protoc-gen-swagger/options/annotations_pb.d.ts
  console/src/app/proto/generated/protoc-gen-swagger/options/annotations_pb.js
  console/src/app/proto/generated/validate/validate_pb.d.ts
  console/src/app/proto/generated/validate/validate_pb.js
Labels: enhancement, frontend, javascript

#365 chore(console): delete evil js
  console/src/app/proto/generated/admin_grpc_web_pb.d.ts
  console/src/app/proto/generated/admin_grpc_web_pb.js
  console/src/app/proto/generated/admin_pb.d.ts
  console/src/app/proto/generated/admin_pb.js
Labels: frontend, javascript

#371 fix(postgres): env variables for notification corrected
  cmd/zitadel/startup.yaml
Labels: bug, go

#387 feat(console): replace wget with curl, user login prompt, warn dialog
  build/console/generate-grpc.sh
  console/src/app/app.module.ts
  console/src/app/modules/accounts-card/accounts-card.component.html
  console/src/app/modules/accounts-card/accounts-card.component.ts
  console/src/app/modules/user-grants/user-grants-datasource.ts
  console/src/app/modules/user-grants/user-grants.component.ts
  console/src/app/modules/warn-dialog/warn-dialog.component.html
  console/src/app/modules/warn-dialog/warn-dialog.component.scss
  console/src/app/modules/warn-dialog/warn-dialog.component.spec.ts
  console/src/app/modules/warn-dialog/warn-dialog.component.ts
  console/src/app/modules/warn-dialog/warn-dialog.module.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/orgs.module.ts
  console/src/assets/environment.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#390 fix(console): pins, translated changes, homepage links
  console/src/app/modules/changes/changes.component.html
  console/src/app/modules/changes/changes.component.ts
  console/src/app/pages/granted-projects/granted-project-grid/granted-project-grid.component.html
  console/src/app/pages/granted-projects/granted-project-grid/granted-project-grid.component.ts
  console/src/app/pages/home/home.component.html
  console/src/app/pages/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/owned-projects/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/owned-projects/owned-project-grid/owned-project-grid.component.ts
  console/src/app/pages/owned-projects/owned-project-list/owned-project-list.component.html
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#293 chore(console): improve text
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: documentation, frontend

#397 fix(console): json missing ,
  console/src/assets/i18n/en.json
Labels: bug, frontend

#398 fix(console): i18n keys
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#471 fix(console): initialize org owner with or without password
  console/src/app/app.component.ts
  console/src/app/pages/orgs/org-create/org-create.component.html
  console/src/app/pages/orgs/org-create/org-create.component.scss
  console/src/app/pages/orgs/org-create/org-create.component.ts
  console/src/app/pages/orgs/org-create/org-create.module.ts
  console/src/app/pages/orgs/password-policy/password-policy.component.scss
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-list/user-list.component.html
  console/src/app/services/org.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#523 chore(console): update dependencies
  console/package-lock.json
  console/package.json
Labels: dependencies, frontend

#526 chore(readme): improve text
  README.md
Labels: documentation

#511 fix(console): hide granted project navigation if none, cache zitadel permissions, emit refresh on org change, cleanup contributors, styling
  console/src/app/animations.ts
  console/src/app/app.component.html
  console/src/app/app.component.scss
  console/src/app/app.component.ts
  console/src/app/directives/has-role/has-role.directive.ts
  console/src/app/guards/role.guard.ts
  console/src/app/modules/avatar/avatar.component.scss
  console/src/app/modules/card/card.scss
  console/src/app/modules/changes/changes.component.html
  console/src/app/modules/changes/changes.component.scss
  console/src/app/modules/changes/changes.component.ts
  console/src/app/modules/contributors/contributors.component.html
  console/src/app/modules/contributors/contributors.component.ts
  console/src/app/modules/project-roles/project-roles.component.html
  console/src/app/modules/project-roles/project-roles.module.ts
  console/src/app/modules/user-grants/user-grants.component.html
  console/src/app/modules/user-grants/user-grants.module.ts
  console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-grid/granted-project-grid.component.html
  console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-list.component.html
  console/src/app/pages/projects/granted-projects/granted-projects.module.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.module.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/project-grants/project-grants.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-grid/owned-project-grid.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.html
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.ts
  console/src/app/pages/projects/owned-projects/owned-projects.module.ts
  console/src/app/pages/users/user-detail/auth-user-detail/theme-setting/theme-card.scss
  console/src/app/pages/users/user-detail/auth-user-detail/theme-setting/theme-setting.component.scss
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.ts
  console/src/app/pipes/has-role.pipe.ts
  console/src/app/services/auth-user.service.ts
  console/src/app/services/auth.service.ts
  console/src/component-themes.scss
  console/src/styles/changes.scss
  console/src/styles/sidenav-list.scss
Labels: enhancement, frontend

#530 docs: Update README.md
  README.md
Labels: documentation, enhancement

#541 Optimize CodeQL analysis
  .github/workflows/codeql-analysis.yml
Labels: enhancement
