Repository zitadel/zitadel, pull requests merged in 2020-08, with the labels that each got.

#574 fix(console): update dependabot deps
  console/package-lock.json
  console/package.json
Labels: dependencies, frontend

#575 feat(console): app compliance messages, dev mode
  console/src/app/pages/projects/apps/app-detail/app-detail.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.scss
  console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
  console/src/app/pages/projects/apps/apps.module.ts
  console/src/app/services/project.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#585 fix(console): rm mfa link, policy issues, consistency for table spacing
  console/src/app/app.component.html
  console/src/app/pages/iam/iam-members/iam-members.component.ts
  console/src/app/pages/orgs/org-create/org-create.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/org-members/org-members.component.ts
  console/src/app/pages/orgs/password-policy/password-policy.component.html
  console/src/app/pages/projects/granted-projects/granted-project-list/granted-project-list.component.scss
  console/src/app/pages/projects/owned-projects/owned-project-detail/applications/applications.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-list/owned-project-list.component.scss
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.html
  console/src/app/pages/users/user-detail/user-detail/user-mfa/user-mfa.component.html
  console/src/app/services/auth.service.ts
  console/src/app/services/grpc.service.ts
Labels: frontend, javascript

#645 fix(console): project grant members, update deps
  console/package-lock.json
  console/package.json
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
Labels: frontend

#651 fix(console): mfa refresh after verification, member eventemitter
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/org-members/org-members.component.html
  console/src/app/pages/orgs/org-members/org-members.component.scss
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-mfa/auth-user-mfa.component.ts
Labels: frontend

#659 fix(console): prompted login
  console/src/app/modules/contributors/contributors.component.html
  console/src/app/modules/contributors/contributors.component.scss
  console/src/app/modules/contributors/contributors.component.ts
  console/src/app/pages/iam/iam.component.html
  console/src/app/pages/iam/iam.component.ts
  console/src/app/pages/orgs/org-detail/org-detail.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.scss
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/orgs/orgs.module.ts
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.html
  console/src/app/pages/projects/granted-projects/granted-project-detail/granted-project-detail.component.ts
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.html
  console/src/app/pages/projects/owned-projects/owned-project-detail/owned-project-detail.component.ts
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/services/authentication.service.ts
Labels: frontend

#664 feat(console): service user detail view, keys cr_d, fix search user autocomplete
  console/src/app/app-routing.module.ts
  console/src/app/app.component.html
  console/src/app/app.module.ts
  console/src/app/modules/search-user-autocomplete/search-user-autocomplete.component.html
  console/src/app/pages/home/home.component.html
  console/src/app/pages/users/user-create-machine/user-create-machine.component.html
  console/src/app/pages/users/user-create-machine/user-create-machine.component.ts
  console/src/app/pages/users/user-create/user-create.component.html
  console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.component.html
  console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.component.scss
  console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.component.spec.ts
  console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.component.ts
  console/src/app/pages/users/user-detail/detail-form-machine/detail-form-machine.module.ts
  console/src/app/pages/users/user-detail/detail-form/detail-form.component.ts
  console/src/app/pages/users/user-detail/machine-keys/add-key-dialog/add-key-dialog.component.html
  console/src/app/pages/users/user-detail/machine-keys/add-key-dialog/add-key-dialog.component.scss
  console/src/app/pages/users/user-detail/machine-keys/add-key-dialog/add-key-dialog.component.spec.ts
  console/src/app/pages/users/user-detail/machine-keys/add-key-dialog/add-key-dialog.component.ts
  console/src/app/pages/users/user-detail/machine-keys/add-key-dialog/add-key-dialog.module.ts
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.html
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.scss
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.spec.ts
  console/src/app/pages/users/user-detail/machine-keys/machine-keys.component.ts
  console/src/app/pages/users/user-detail/user-detail.module.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
  console/src/app/pages/users/user-list/user-list-routing.module.ts
  console/src/app/pages/users/user-list/user-list.component.html
  console/src/app/pages/users/user-list/user-list.component.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/services/mgmt-user.service.ts
  console/src/assets/environment.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
Labels: frontend

#654 fix: cookie handling
  cmd/zitadel/main.go
  cmd/zitadel/startup.yaml
  go.mod
  go.sum
  internal/api/http/cookie.go
  internal/api/http/header.go
  internal/api/http/middleware/security_headers.go
  internal/api/http/middleware/user_agent_cookie.go
  internal/api/http/user_agent_cookie.go
  internal/api/oidc/auth_request.go
  internal/api/oidc/cookie_interceptor.go
  internal/api/oidc/op.go
  internal/auth/repository/auth_request.go
  internal/auth/repository/eventsourcing/eventstore/auth_request.go
  internal/ui/console/console.go
  internal/ui/login/handler/auth_request.go
  internal/ui/login/handler/login.go
  internal/ui/login/handler/login_handler.go
  internal/ui/login/handler/mfa_verify_handler.go
  internal/ui/login/handler/password_handler.go
  internal/ui/login/handler/renderer.go
  internal/ui/login/handler/select_user_handler.go
  internal/ui/login/login.go
  internal/ui/login/static/i18n/de.yaml
  internal/ui/login/static/i18n/en.yaml
  internal/ui/ui.go
Labels: bug, enhancement
