Repository zitadel/zitadel, pull requests merged in 2021-06, with the labels that each got.

#1754 chore(contribute): add step by step guide
  CONTRIBUTING.md
  build/README.md
  build/console/generate-static.sh
  build/docker-compose-debug.yml
  build/docker-compose-dev.yml
  build/dockerfile
  build/local/Dockerfile.clientid
  build/local/Dockerfile.gateway
  build/local/Dockerfile.keys
  build/local/Dockerfile.started
  build/local/clientid.sh
  build/local/docker-compose-local.yml
  build/local/environment.json
  build/local/keys.sh
  build/local/local.env
  build/local/zitadel-started.sh
  build/login/generate-static.sh
  build/notification/generate-static.sh
  build/zitadel/generate-openapi-static.sh
  build/zitadel/generate-static.sh
  cmd/zitadel/caos_local.sh
  cmd/zitadel/main.go
  guides/development.md
  guides/production.md
  guides/quickstart.md
  internal/notification/repository/eventsourcing/handler/notification.go
  internal/query/query.go
  internal/ui/login/handler/login.go
Labels: docker, documentation

#1863 fix: add hint for password-confirmation
  console/src/assets/i18n/en.json
  internal/static/i18n/en.yaml
  internal/ui/login/handler/password_complexity_policy_handler.go
  internal/ui/login/static/i18n/de.yaml
  internal/ui/login/static/i18n/en.yaml
  internal/ui/login/static/resources/scripts/change_password_check.js
  internal/ui/login/static/resources/scripts/init_password_check.js
  internal/ui/login/static/resources/scripts/password_policy_check.js
  internal/ui/login/static/resources/scripts/register_check.js
Labels: bug, frontend

#1930 chore(dependencies): set labels for dependabot PR
  .github/dependabot.yml
Labels: dependencies

#1894 feat: enable running ZITADEL offline
  operator/common/images.go
  operator/common/images_test.go
  operator/database/kinds/backups/backups.go
  operator/database/kinds/backups/bucket/adapt.go
  operator/database/kinds/backups/bucket/adapt_test.go
  operator/database/kinds/backups/bucket/backup/adapt.go
  operator/database/kinds/backups/bucket/backup/adapt_test.go
  operator/database/kinds/backups/bucket/backup/job.go
  operator/database/kinds/backups/bucket/backup/job_test.go
  operator/database/kinds/backups/bucket/clean/adapt.go
  operator/database/kinds/backups/bucket/clean/adapt_test.go
  operator/database/kinds/backups/bucket/clean/job.go
  operator/database/kinds/backups/bucket/clean/job_test.go
  operator/database/kinds/backups/bucket/restore/adapt.go
  operator/database/kinds/backups/bucket/restore/adapt_test.go
  operator/database/kinds/backups/bucket/restore/job.go
  operator/database/kinds/backups/bucket/restore/job_test.go
  operator/database/kinds/databases/databases.go
  operator/database/kinds/databases/managed/adapt.go
  operator/database/kinds/databases/managed/adapt_backup_test.go
  operator/database/kinds/databases/managed/adapt_test.go
  operator/database/kinds/orb/adapt.go
  operator/database/kinds/orb/desired.go
  operator/database/kinds/orb/reconcile.go
  operator/zitadel/kinds/iam/iam.go
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/deployment/adapt.go
  operator/zitadel/kinds/iam/zitadel/deployment/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/deployment/container.go
  operator/zitadel/kinds/iam/zitadel/deployment/container_test.go
  operator/zitadel/kinds/iam/zitadel/deployment/initcontainer.go
  operator/zitadel/kinds/iam/zitadel/deployment/initcontainer_test.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/migration/migrationcontainer.go
  operator/zitadel/kinds/iam/zitadel/migration/postcontainer.go
  operator/zitadel/kinds/iam/zitadel/migration/precontainer.go
  operator/zitadel/kinds/iam/zitadel/migration/precontainer_test.go
  operator/zitadel/kinds/iam/zitadel/setup/adapt.go
  operator/zitadel/kinds/iam/zitadel/setup/adapt_test.go
  operator/zitadel/kinds/orb/adapt.go
  operator/zitadel/kinds/orb/desired.go
  operator/zitadel/kinds/orb/reconcile.go
  pkg/kubernetes/artifacts.go
Labels: enhancement, operator

#1934 chore(issues): add links to discussions for feature requests
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#1810 feat(eventstore): previous aggregate root sequence
  internal/command/main_test.go
  internal/eventstore/event.go
  internal/eventstore/event_base.go
  internal/eventstore/eventstore_test.go
  internal/eventstore/handler/crdb/handler_stmt.go
  internal/eventstore/handler/crdb/handler_stmt_test.go
  internal/eventstore/handler/crdb/reduce.go
  internal/eventstore/handler/handler_projection_test.go
  internal/eventstore/handler/statement.go
  internal/eventstore/repository/event.go
  internal/eventstore/repository/sql/crdb.go
  internal/eventstore/repository/sql/query.go
  internal/eventstore/repository/sql/query_test.go
  internal/eventstore/v1/internal/repository/sql/db_mock_test.go
  internal/eventstore/v1/internal/repository/sql/query.go
  internal/eventstore/v1/internal/repository/sql/query_test.go
  internal/query/projection/org.go
  internal/query/projection/org_admin.go
  internal/query/projection/projection.go
  migrations/cockroach/V1.47__es_previous_agg_root_seq.sql
  migrations/cockroach/V1.60__zitadel_schema.sql
Labels: backend, go
