Repository zitadel/zitadel, pull requests merged in 2021-02, with the labels that each got.

#1233 chore(console): dependencies
  console/package-lock.json
  console/package.json
  site/package-lock.json
  site/package.json
Labels: dependencies, frontend

#1227 fix: don't enable database features for user operations
  pkg/databases/connection.go
  pkg/databases/user.go
Labels: bug, operator

#1192 fix: fetch org context in guard, more main content space
  console/src/app/app.component.scss
  console/src/app/guards/auth.guard.ts
Labels: bug, frontend

#1237 fix(login): mail verification
  internal/ui/login/static/templates/mail_verification.html
Labels: bug, frontend

#1240 fix: update ORBOS
  .gitignore
  go.mod
  go.sum
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/grpc/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/http/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/ui/adapt.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt.go
  operator/zitadel/kinds/iam/zitadel/services/adapt.go
  operator/zitadel/kinds/iam/zitadel/services/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/services/clientid.go
Labels: dependencies

#1273 fix(pipeline): corrected and combined operator and zitadel release into combined workflow
  .github/workflows/operator.yml
  .github/workflows/zitadel.yml
  .releaserc.js
  go.sum
Labels: bug, enhancement, semantic-release

#1277 chore(pipeline): use correct path to zitadelctl binaries
  .releaserc.js
Labels: bug, enhancement, semantic-release

#1278 fix(pipeline): use correct version for zitadelctl build
  .github/workflows/zitadel.yml
Labels: bug, semantic-release

#1297 fix(login): primary button color
  internal/ui/login/static/templates/link_users_done.html
Labels: frontend
