Repository zitadel/zitadel, pull requests merged in 2021-04, with the labels that each got.

#1621 docs: logo in readme
  README.md
  docs/static/logos/zitadel-logo-dark@2x.png
Labels: documentation

#1625 refactor: Version 1
  SECURITY.md
Labels: documentation

#1628 docs(search): integrated algolia (thank you 🥳 )
  docs/docusaurus.config.js
Labels: documentation, enhancement

#1631 fix(console): link to quickstarts
  console/src/app/pages/home/home.component.html
  docs/sidebars.js
Labels: documentation, enhancement, frontend

#1644 docs: fix CAP theorem acronym resolution
  docs/docs/concepts/architecture.md
Labels: documentation

#1651 chore(pipeline): change caching keys
  .dockerignore
  .github/workflows/codecov.yml
  .github/workflows/zitadel.yml
  build/dockerfile
Labels: enhancement

#1660 fix(operator): use latest ORBOS
  go.mod
  go.sum
Labels: operator

#1679 chore(dependabot): schedule time
  .github/dependabot.yml
Labels: dependencies, enhancement

#1634 feat(operator): enable specifying custom acme authority for subdomains
  cmd/zitadelctl/cmds/backup.go
  cmd/zitadelctl/cmds/configure.go
  cmd/zitadelctl/cmds/readsecret.go
  cmd/zitadelctl/cmds/restore.go
  cmd/zitadelctl/cmds/takeoff.go
  cmd/zitadelctl/cmds/writesecret.go
  go.mod
  go.sum
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/hosts/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/hosts/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/configuration/desired.go
  operator/zitadel/kinds/iam/zitadel/desired.go
Labels: enhancement, go
