Repository zitadel/zitadel, pull requests merged in 2021-07, with the labels that each got.

#1878 fix: add option to disable asset storage
  internal/command/statics.go
  internal/management/repository/eventsourcing/handler/label_policy.go
  internal/static/config/config.go
Labels: backend, go

#1944 feat: sentry integration
  cmd/zitadel/main.go
  go.mod
  go.sum
  internal/api/assets/asset.go
  internal/api/grpc/server/middleware/sentry_interceptor.go
  internal/api/grpc/server/middleware/translator.go
  internal/api/grpc/server/server.go
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/configuration/desired.go
  operator/zitadel/kinds/iam/zitadel/configuration/literals.go
  operator/zitadel/kinds/iam/zitadel/configuration/literals_test.go
  operator/zitadel/kinds/iam/zitadel/deployment/container.go
  operator/zitadel/kinds/iam/zitadel/deployment/container_test.go
  operator/zitadel/kinds/iam/zitadel/secrets.go
Labels: angular, backend, enhancement, go, operator

#1984 docs: update to beta 3
  docs/package.json
  docs/yarn.lock
Labels: documentation

#1982 docs: eventstore
  docs/docs/concepts/eventstore.md
  docs/sidebars.js
Labels: documentation

#1997 fix: give restore more time
  operator/database/kinds/backups/bucket/restore/adapt.go
Labels: bug, operator

#1685 fix(zitadelctl): implementation for commands in crd mode
  cmd/zitadelctl/cmds/backup.go
  cmd/zitadelctl/cmds/backuplist.go
  cmd/zitadelctl/cmds/destroy.go
  cmd/zitadelctl/cmds/restore.go
  cmd/zitadelctl/cmds/takeoff.go
  cmd/zitadelctl/main.go
  internal/ui/login/handler/login.go
  operator/crtlcrd/backup.go
  operator/crtlcrd/database/destroy.go
  operator/crtlcrd/destroy.go
  operator/crtlcrd/zitadel/destroy.go
  operator/crtlgitops/destroy.go
  operator/crtlgitops/start.go
  operator/database/destroy.go
  operator/database/kinds/backups/backups.go
  operator/database/kinds/backups/bucket/adapt.go
  operator/database/kinds/backups/bucket/adapt_test.go
  operator/database/kinds/backups/bucket/clean/adapt.go
  operator/database/kinds/backups/bucket/clean/adapt_test.go
  operator/database/kinds/backups/bucket/clean/command.go
  operator/database/kinds/backups/bucket/clean/command_test.go
  operator/database/kinds/backups/bucket/list.go
  operator/database/kinds/backups/bucket/mock.go
  operator/database/kinds/backups/core/list.go
  operator/database/kinds/databases/core/current.go
  operator/database/kinds/databases/core/dblist.go
  operator/database/kinds/databases/databases.go
  operator/database/kinds/databases/managed/adapt.go
  operator/database/kinds/databases/managed/adapt_backup_test.go
  operator/database/kinds/databases/managed/listbackups.go
  operator/database/kinds/databases/managed/rbac/adapt.go
  operator/database/kinds/orb/adapt.go
  operator/database/kinds/orb/backups.go
  operator/database/kinds/orb/reconcile.go
  operator/zitadel/destroy.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt.go
  operator/zitadel/kinds/iam/zitadel/setup/adapt.go
  operator/zitadel/kinds/orb/adapt.go
  operator/zitadel/kinds/orb/reconcile.go
  pkg/databases/backup.go
  pkg/databases/backuplist.go
  pkg/databases/clear.go
  pkg/databases/connection.go
  pkg/databases/restore.go
  pkg/kubernetes/artifacts.go
  pkg/zitadel/clearmigraterestore.go
  pkg/zitadel/migration.go
  pkg/zitadel/zitadel.go
Labels: bug, enhancement, operator

#2047 docs: additional terms for dedicated instance
  docs/docs/legal/dedicated-instance-annex.md
  docs/docs/legal/service-level-description.md
  docs/docs/legal/support-services.md
  docs/docs/legal/terms-of-service-dedicated.md
  docs/docs/legal/terms-of-service.md
  docs/sidebars.js
Labels: documentation

#2077 fix: return unsuccessful code on failure
  cmd/zitadelctl/cmds/root.go
Labels: bug, operator

#2076 chore(dev): linux dev support workaround
  build/local/Dockerfile.started
  build/local/clientid.sh
  build/local/docker-compose-local.yml
  build/local/zitadel-started.sh
  build/zitadel/Dockerfile
  guides/quickstart.md
Labels: bug, enhancement
