Repository zitadel/zitadel, pull requests merged in 2021-03, with the labels that each got.

#1375 fix(operator): correct ambassador mapping and host, and fix applied migration
  go.mod
  go.sum
  operator/start/start.go
  operator/zitadel/kinds/iam/zitadel/ambassador/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/ambassador/hosts/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/setup/adapt.go
Labels: bug, enhancement

#1412 docs(oidc): correct some typos
  site/docs/architecture/03-openidoauth.md
Labels: documentation

#1435 feat: Add read and writesecret options for crd mode
  cmd/database-debug/main.go
  cmd/operator-debug/main.go
  cmd/zitadelctl/cmds/backup.go
  cmd/zitadelctl/cmds/readsecret.go
  cmd/zitadelctl/cmds/restore.go
  cmd/zitadelctl/cmds/root.go
  cmd/zitadelctl/cmds/start.go
  cmd/zitadelctl/cmds/takeoff.go
  cmd/zitadelctl/cmds/writesecret.go
  go.mod
  go.sum
  operator/adapt.go
  operator/api/core/api.go
  operator/api/database/api.go
  operator/api/zitadel/api.go
  operator/crtlcrd/controller.go
  operator/crtlcrd/database/database.go
  operator/crtlcrd/zitadel/zitadel.go
  operator/crtlgitops/start.go
  operator/database/kinds/backups/backups.go
  operator/database/kinds/backups/bucket/adapt.go
  operator/database/kinds/backups/bucket/adapt_test.go
  operator/database/kinds/backups/bucket/secrets.go
  operator/database/kinds/backups/bucket/secrets_test.go
  operator/database/kinds/databases/databases.go
  operator/database/kinds/databases/managed/adapt.go
  operator/database/kinds/databases/managed/adapt_backup_test.go
  operator/database/kinds/databases/managed/adapt_test.go
  operator/database/kinds/databases/provided/adapt.go
  operator/database/kinds/orb/adapt.go
  operator/database/takeoff.go
  operator/secrets/secrets.go
  operator/zitadel/kinds/iam/iam.go
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/grpc/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/hosts/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/ambassador/http/adapt.go
  operator/zitadel/kinds/iam/zitadel/ambassador/ui/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/configuration/users/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/configuration/users/users_test.go
  operator/zitadel/kinds/iam/zitadel/database/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/database/client.go
  operator/zitadel/kinds/iam/zitadel/database/mock/client.mock.go
  operator/zitadel/kinds/iam/zitadel/database/user.go
  operator/zitadel/kinds/iam/zitadel/secrets.go
  operator/zitadel/kinds/iam/zitadel/services/adapt.go
  operator/zitadel/kinds/iam/zitadel/services/adapt_test.go
  operator/zitadel/kinds/orb/adapt.go
  operator/zitadel/kinds/orb/desired.go
  operator/zitadel/kinds/orb/zz_generated.deepcopy.go
  operator/zitadel/takeoff.go
  pkg/databases/backup.go
  pkg/databases/clear.go
  pkg/databases/connection.go
  pkg/databases/restore.go
  pkg/databases/user.go
  pkg/kubernetes/artifacts.go
  scripts/operator-debug.sh
Labels: enhancement, operator

#1385 fix: Crdoperatormerge review
  .github/workflows/zitadel.yml
  cmd/zitadelctl/cmds/root.go
  cmd/zitadelctl/cmds/takeoff.go
  go.sum
  operator/database/kinds/backups/bucket/backup/adapt_test.go
  operator/database/kinds/backups/bucket/backup/cleanup_test.go
  operator/database/kinds/backups/bucket/clean/adapt_test.go
  operator/database/kinds/backups/bucket/restore/adapt_test.go
  operator/zitadel/kinds/iam/zitadel/configuration/literals_test.go
Labels: operator

#1458 fix(operator): Standard timeout handling
  go.mod
  go.sum
  operator/database/kinds/backups/bucket/backup/adapt.go
  operator/database/kinds/backups/bucket/clean/adapt.go
  operator/database/kinds/backups/bucket/restore/adapt.go
  operator/database/kinds/databases/managed/adapt_backup_test.go
  operator/database/kinds/databases/managed/adapt_test.go
  operator/database/kinds/databases/managed/statefulset/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/adapt.go
  operator/zitadel/kinds/iam/zitadel/deployment/adapt.go
  operator/zitadel/kinds/iam/zitadel/deployment/ready.go
Labels: bug

#1475 fix: gitops backup and restore need a kubernetes client too
  cmd/zitadelctl/cmds/backup.go
  cmd/zitadelctl/cmds/restore.go
Labels: bug, operator

#1466 fix: revert migration V1.13
  internal/eventstore/local_crdb_test.go
  internal/eventstore/repository/sql/local_crdb_test.go
  migrations/cockroach/V1.13__machine_keys_public.sql
Labels: bug

#1492 fix: Example client
  .gitignore
  build/zitadel/generate-grpc-clients.sh
  examples/client/Dockerfile
  examples/client/README.md
  examples/client/go.mod
  examples/client/go.sum
  examples/client/main.go
Labels: documentation
