Repository zitadel/zitadel, pull requests merged in 2021-05, with the labels that each got.

#1712 docs(api): correct link to latest admin api
  docs/docs/apis/apis.md
Labels: documentation

#1713 docs: fix email writesecret command
  docs/docs/guides/installation/crd.md
  docs/docs/guides/installation/gitops.md
Labels: bug, documentation

#1739 chore(deps): update docusaurus
  docs/package-lock.json
  docs/package.json
  docs/yarn.lock
Labels: dependencies, documentation

#1716 chore: remove PAT and use GH Token
  .github/workflows/zitadel.yml
  README.md
Labels: enhancement

#1744 docs: changes acme to acme-caos
  docs/docs/guides/usage/projects.md
Labels: documentation

#1745 docs: update run and start section texts
  README.md
Labels: documentation

#1782 chore(coc): recommend code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation
