Repository zitadel/zitadel, pull requests merged in 2021-09, with the labels that each got.

#2308 chore(backend): update dependencies
  build/local/Dockerfile.gateway
  build/zitadel/Dockerfile
  go.mod
  go.sum
  internal/telemetry/metrics/otel/open_telemetry.go
Labels: dependencies, gomod

#1692 docs: generate zitadel keys
  docs/docs/guides/installation/crd.md
  docs/docs/guides/installation/templates/example_keys
Labels: documentation, operator

#2078 fix: writesecret with --gitops doesn't need a kubeconfig
  cmd/zitadelctl/cmds/writesecret.go
Labels: bug, operator

#2087 fix: return 1 on CLI misusage
  cmd/zitadelctl/main.go
Labels: go, operator
