Repository zitadel/zitadel, pull requests merged in 2021-08, with the labels that each got.

#2136 fix(build): update go version to 1.16 and dependencies
  build/operator/Dockerfile
  build/zitadel/Dockerfile
  go.mod
  go.sum
  internal/api/api.go
  internal/telemetry/metrics/metrics.go
  internal/telemetry/metrics/otel/open_telemetry.go
  internal/telemetry/tracing/google/google_tracer.go
  internal/telemetry/tracing/log/config.go
  internal/telemetry/tracing/otel/config.go
  internal/telemetry/tracing/otel/open_telemetry.go
  internal/telemetry/tracing/span.go
  internal/telemetry/tracing/tracing.go
Labels: dependencies, go, backend, gomod

#2138 fix(operator): update cockroach and flyway versions
  operator/common/images.go
Labels: dependencies

#2127 docs: added setup options to docs
  docs/docs/guides/installation/checkup.md
  docs/docs/guides/installation/setup-orbos.md
  docs/docs/guides/installation/setup.md
  docs/sidebars.js
Labels: documentation

#2234 docs(legal): add support service tos
  docs/docs/guides/trainings/introduction.md
  docs/docs/guides/trainings/supportservice/application.md
  docs/docs/guides/trainings/supportservice/operations.md
  docs/docs/guides/trainings/supportservice/recurring.md
  docs/docs/legal/support-services.md
  docs/docs/legal/terms-support-service.md
  docs/sidebars.js
  docs/static/img/training_support_services.png
Labels: documentation

#2266 fix: increase instant backup timeout
  operator/database/kinds/backups/bucket/backup/adapt.go
Labels: bug, operator
