Repository zitadel/zitadel, pull requests merged in 2022-01, with the labels that each got.

#2843 fix(k8s): new generated crd-definitions for k8s 1.22
  operator/zitadel/kinds/orb/zz_generated.deepcopy.go
  pkg/kubernetes/artifacts.go
  scripts/generateCrd.sh
Labels: bug, enhancement

#3032 chore: proxy plausible
  docs/docusaurus.config.js
Labels: documentation, enhancement, javascript

#3025 docs: update angular quickstart
  docs/docs/quickstarts/login/angular.md
Labels: documentation

#3080 docs: add MongoDB Authenticated Charts integration guide
  docs/docs/guides/integrations/authenticated-mongodb-charts.md
  docs/docs/guides/overview.mdx
  docs/sidebars.js
  docs/static/img/integrations/mongodb-charts-app-create-light.png
  docs/static/img/integrations/mongodb-charts-auth-provider-light.png
Labels: documentation
