Repository zitadel/zitadel, pull requests merged in 2022-06, with the labels that each got.

#3823 docs(legal): Updated agreements and policies v2
  docs/docs/legal/_piid-table.mdx
  docs/docs/legal/cloud-service-description.md
  docs/docs/legal/data-processing-agreement.mdx
  docs/docs/legal/dedicated-instance-annex.md
  docs/docs/legal/privacy-policy.mdx
  docs/docs/legal/service-level-description.md
  docs/docs/legal/support-services.md
  docs/docs/legal/terms-of-service-dedicated.md
  docs/docs/legal/terms-of-service.md
  docs/docs/legal/terms-support-service.md
  docs/sidebars.js
  internal/qrcode/readme.md
Labels: documentation

#3819 feat: enable insecure console for custom domains
  console/src/app/services/grpc.service.ts
Labels: enhancement, question

#3817 docs(installation): improve guides
  deploy/compose/docker-compose.yml
  docs/docs/guides/installation/compose.mdx
  docs/docs/guides/installation/configuration.mdx
  docs/docs/guides/installation/configure/compose.mdx
  docs/docs/guides/installation/configure/configure.mdx
  docs/docs/guides/installation/configure/docker-compose.yaml
  docs/docs/guides/installation/configure/example-zitadel-config.yaml
  docs/docs/guides/installation/configure/example-zitadel-init-steps.yaml
  docs/docs/guides/installation/configure/example-zitadel-secrets.yaml
  docs/docs/guides/installation/configure/example-zitadel-values-secrets.yaml
  docs/docs/guides/installation/configure/example-zitadel-values.yaml
  docs/docs/guides/installation/configure/helm.mdx
  docs/docs/guides/installation/configure/linuxunix.mdx
  docs/docs/guides/installation/configure/windows.mdx
  docs/docs/guides/installation/custom-domain.md
  docs/docs/guides/installation/get-started/compose.mdx
  docs/docs/guides/installation/get-started/docker-compose.yaml
  docs/docs/guides/installation/get-started/get-started.mdx
  docs/docs/guides/installation/get-started/helm.mdx
  docs/docs/guides/installation/get-started/linux.mdx
  docs/docs/guides/installation/get-started/macos.mdx
  docs/docs/guides/installation/get-started/nextselfhosted.mdx
  docs/docs/guides/installation/get-started/windows.mdx
  docs/docs/guides/installation/helm.mdx
  docs/docs/guides/installation/http2-support.md
  docs/docs/guides/installation/linux.mdx
  docs/docs/guides/installation/loadbalancing-example/docker-compose.yaml
  docs/docs/guides/installation/loadbalancing-example/example-zitadel-config.yaml
  docs/docs/guides/installation/loadbalancing-example/example-zitadel-init-steps.yaml
  docs/docs/guides/installation/loadbalancing-example/example-zitadel-secrets.yaml
  docs/docs/guides/installation/loadbalancing-example/loadbalancing-example.md
  docs/docs/guides/installation/loadbalancing-example/traefik.yaml
  docs/docs/guides/installation/macos.mdx
  docs/docs/guides/installation/openlocal.mdx
  docs/docs/guides/installation/windows.mdx
  docs/sidebars.js
  example-zitadel-config.yaml
Labels: documentation

#3838 docs(guides): user metadata
  docs/docs/guides/customization/user-metadata.md
  docs/sidebars.js
  docs/static/img/console_projects_application_token_settings.png
Labels: documentation

#3880 docs(installation): fix overview items
  docs/docs/guides/installation/configure/configure.mdx
  docs/docs/guides/installation/configure/helm.mdx
  docs/docs/guides/installation/run/compose.mdx
  docs/docs/guides/installation/run/docker-compose.yaml
  docs/docs/guides/installation/run/helm.mdx
  docs/docs/guides/installation/run/knative.mdx
  docs/docs/guides/installation/run/linux.mdx
  docs/docs/guides/installation/run/macos.mdx
  docs/docs/guides/installation/run/nextselfhosted.mdx
  docs/docs/guides/installation/run/run.mdx
  docs/docs/guides/installation/run/windows.mdx
  docs/docs/guides/overview.mdx
  docs/docs/legal/data-processing-agreement.mdx
  docs/docs/legal/terms-support-service.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/src/pages/index.js
Labels: bug, documentation, enhancement
