Repository zitadel/zitadel, pull requests merged in 2022-07, with the labels that each got.

#3878 docs(installation): fix guides
  docs/docs/guides/installation/configure/docker-compose.yaml
  docs/docs/guides/installation/loadbalancing-example/docker-compose.yaml
  docs/docs/guides/installation/loadbalancing-example/loadbalancing-example.md
Labels: bug, documentation

#3905 docs: improve eventstore docs
  docs/docs/concepts/eventstore/overview.md
  docs/docs/guides/installation/configure/configure.mdx
  docs/docs/guides/installation/run/compose.mdx
Labels: bug, documentation, enhancement, v2

#3947 docs(installation): document masterkey config
  docs/docs/guides/installation/configure/configure.mdx
Labels: documentation, enhancement, v2

#3946 fix(docs): image zoom plugin
  docs/docusaurus.config.js
  docs/package.json
  docs/yarn.lock
Labels: documentation

#3974 docs(installation): inline file contents
  docs/docs/guides/installation/configure/compose.mdx
  docs/docs/guides/installation/configure/configure.mdx
  docs/docs/guides/installation/configure/helm.mdx
  docs/docs/guides/installation/configure/linuxunix.mdx
  docs/docs/guides/installation/loadbalancing-example/loadbalancing-example.mdx
  docs/docs/guides/installation/run/compose.mdx
  docs/docs/guides/installation/run/knative.mdx
  docs/docs/guides/installation/run/linux.mdx
  docs/package.json
  docs/yarn.lock
Labels: documentation

#3971 feat(export): additional options for exporting
  docs/docs/apis/proto/admin.md
  internal/api/grpc/admin/export.go
  proto/zitadel/admin.proto
Labels: type: enhancement, lang: go, category: backend

#3798 feat: V2 alpha import and export of organizations
  .releaserc.js
  build/zitadel/generate-grpc.sh
  cmd/start/start.go
  docs/docs/apis/proto/admin.md
  docs/docs/apis/proto/management.md
  docs/docs/apis/proto/system.md
  docs/docs/apis/proto/v1.md
  docs/docs/guides/api/export-and-import.md
  docs/sidebars.js
  go.mod
  go.sum
  internal/api/grpc/admin/domain_policy.go
  internal/api/grpc/admin/export.go
  internal/api/grpc/admin/import.go
  internal/api/grpc/admin/server.go
  internal/api/grpc/management/actions.go
  internal/api/grpc/management/actions_converter.go
  internal/api/grpc/management/idp.go
  internal/api/grpc/management/idp_converter.go
  internal/api/grpc/management/idp_converter_test.go
  internal/api/grpc/management/policy_label.go
  internal/api/grpc/management/policy_label_converter.go
  internal/api/grpc/management/policy_login.go
  internal/api/grpc/management/policy_login_converter.go
  internal/api/grpc/management/user.go
  internal/api/grpc/management/user_converter.go
  internal/command/org.go
  internal/command/org_action.go
  internal/command/org_domain.go
  internal/command/org_domain_test.go
  internal/command/org_idp_config.go
  internal/command/project.go
  internal/command/project_application_api.go
  internal/command/project_application_oidc.go
  internal/command/project_grant.go
  internal/command/user_human.go
  internal/command/user_human_otp.go
  internal/command/user_idp_link.go
  internal/command/user_machine.go
  internal/crypto/crypto.go
  internal/domain/human.go
  internal/domain/human_hashed_password.go
  internal/eventstore/handler/handler_projection.go
  internal/query/idp.go
  internal/query/query.go
  internal/query/user_otp.go
  internal/query/user_password.go
  proto/zitadel/admin.proto
  proto/zitadel/management.proto
  proto/zitadel/system.proto
  proto/zitadel/v1.proto
Labels: type: enhancement, lang: go, category: backend

#4079 docs(installation): fix helm command
  docs/docs/guides/deploy/kubernetes.mdx
Labels: type: bug, category: docs

#4080 chore(readme): update links
  README.md
Labels: category: docs
