Repository zitadel/zitadel, pull requests merged in 2022-10, with the labels that each got.

#4505 fix(metadata): corrected handling of remove metadata events
  internal/command/metadata_model.go
  internal/command/user_metadata_model.go
Labels: type: bug, lang: go, category: backend

#4527 ci(e2e): fix typo in workflow
  .github/workflows/e2e.yml
Labels: type: bug, type: fix, category: ci

#4342 test(e2e): test authorizations
  CONTRIBUTING.md
  console/src/app/directives/copy-to-clipboard/copy-to-clipboard.directive.ts
  console/src/app/modules/add-member-dialog/member-create-dialog.component.html
  console/src/app/modules/contributors/contributors.component.html
  console/src/app/modules/info-row/info-row.component.html
  console/src/app/modules/members-table/members-table.component.html
  console/src/app/modules/search-user-autocomplete/search-user-autocomplete.component.html
  console/src/app/modules/sidenav/sidenav.component.html
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/pages/projects/apps/app-create/app-create.component.html
  console/src/app/pages/projects/apps/app-secret-dialog/app-secret-dialog.component.html
  console/src/app/pages/projects/apps/redirect-uris/redirect-uris.component.html
  e2e/cypress/e2e/applications/applications.cy.ts
  e2e/cypress/e2e/humans/humans.cy.ts
  e2e/cypress/e2e/machines/machines.cy.ts
  e2e/cypress/e2e/organization/organizations.cy.ts
  e2e/cypress/e2e/permissions/permissions.cy.ts
  e2e/cypress/e2e/projects/projects.cy.ts
  e2e/cypress/e2e/settings/oidc-settings.cy.ts
  e2e/cypress/e2e/settings/private-labeling.cy.ts
  e2e/cypress/support/api/apiauth.ts
  e2e/cypress/support/api/ensure.ts
  e2e/cypress/support/api/grants.ts
  e2e/cypress/support/api/members.ts
  e2e/cypress/support/api/oidc-settings.ts
  e2e/cypress/support/api/orgs.ts
  e2e/cypress/support/api/policies.ts
  e2e/cypress/support/api/projects.ts
  e2e/cypress/support/api/search.ts
  e2e/cypress/support/api/types.ts
  e2e/cypress/support/api/users.ts
  e2e/cypress/support/commands.ts
  e2e/docker-compose.yaml
  e2e/package-lock.json
  e2e/package.json
Labels: type: enhancement, lang: javascript, state: in progress, category: ci

#4539 docs(azuread): update azuread integration guide
  docs/docs/guides/integrate/azuread-oidc.md
Labels: category: docs

#4541 docs(concepts): update user concept
  docs/docs/apis/openidoauth/grant-types.md
  docs/docs/concepts/features/selfservice.md
  docs/docs/concepts/structure/_user_description.mdx
  docs/docs/concepts/structure/users.md
  docs/docs/guides/integrate/serviceusers.md
Labels: category: docs

#4535 docs(concepts): describe virtual instances
  docs/docs/concepts/structure/_instance_description.mdx
  docs/docs/concepts/structure/instance.mdx
Labels: category: docs

#4567 ci(e2e): give console init time
  e2e/cypress/support/login/users.ts
Labels: category: ci

#4534 fix(export): add export for app and machine keys
  docs/docs/apis/proto/admin.md
  internal/api/grpc/admin/export.go
  internal/query/authn_key.go
  proto/zitadel/admin.proto
Labels: lang: go, category: backend, type: fix

#4578 fix: export of idp links
  internal/api/grpc/admin/export.go
Labels: lang: go, category: backend, type: fix

#4576 fix: import of trigger actions and export of idp links
  docs/docs/apis/proto/v1.md
  internal/api/grpc/admin/export.go
  internal/api/grpc/admin/import.go
  proto/zitadel/v1.proto
Labels: lang: go, category: backend, type: fix

#4579 fix(export): export json marshal to jsonpb
  internal/api/grpc/admin/export.go
Labels: lang: go, category: backend, type: fix

#4580 fix(import): import json marshal to jsonpb
  internal/api/grpc/admin/import.go
Labels: lang: go, category: backend, type: fix

#4603 docs(contributing): remove guides folder
  console/README.md
  guides/development.md
  guides/production.md
  guides/quickstart.md
Labels: category: docs

#4606 fix(saml): update saml dependency
  go.mod
  go.sum
Labels: lang: go, category: backend, type: fix

#4582 docs(training): update trainings
  docs/docs/guides/trainings/application.md
Labels: category: docs

#4605 fix(machine): delete domain policy dependency and restructure functions
  internal/api/grpc/admin/import.go
  internal/api/grpc/management/user.go
  internal/api/grpc/management/user_converter.go
  internal/command/user_machine.go
  internal/command/user_machine_test.go
Labels: lang: go, category: backend, type: fix

#4615 docs(deploy): fix lb example
  docs/docs/guides/deploy/loadbalancing-example/docker-compose.yaml
  docs/docs/guides/deploy/loadbalancing-example/example-zitadel-secrets.yaml
Labels: category: docs, docker, effort: 1

#4173 fix(user): add search query for login name
  docs/docs/apis/proto/user.md
  internal/api/grpc/server/middleware/instance_interceptor.go
  internal/api/grpc/user/query.go
  internal/api/ui/console/console.go
  internal/database/type.go
  internal/eventstore/repository/search_query.go
  internal/query/search_query.go
  internal/query/search_query_test.go
  internal/query/user.go
  proto/zitadel/user.proto
Labels: lang: go, category: backend, type: fix
