Repository zitadel/zitadel, pull requests merged in 2022-08, with the labels that each got.

#4084 docs(development): Remove references to deprecated files, add info on DOCKER_BUILDKIT
  guides/development.md
Labels: category: docs

#4075 chore: change image tags and add docker manifest
  .goreleaser.yaml
Labels: category: infra

#4081 docs(architecture): extend the software and deployment architecture
  docs/docs/concepts/architecture.md
  docs/docs/concepts/architecture/software.md
  docs/docs/concepts/architecture/solution.md
  docs/docs/concepts/eventstore/implementation.md
  docs/docs/concepts/eventstore/overview.md
  docs/sidebars.js
Labels: category: docs

#4101 docs(azuread): guide to use azuread as IdP for ZITADEL
  docs/docs/guides/integrate/azuread.md
  docs/docs/guides/integrate/identity-brokering.md
  docs/sidebars.js
  docs/static/img/guides/azure_app.png
  docs/static/img/guides/azure_app_redirects.png
  docs/static/img/guides/azure_app_register.png
  docs/static/img/guides/azure_app_secrets.png
  docs/static/img/guides/azure_app_token.png
  docs/static/img/guides/azure_login.png
  docs/static/img/guides/azure_zitadel_activate.png
  docs/static/img/guides/azure_zitadel_active.png
  docs/static/img/guides/azure_zitadel_button.png
  docs/static/img/guides/azure_zitadel_settings.png
Labels: category: docs

#4133 fix e2e workflow
  .github/workflows/e2e.yml
Labels: type: bug

#4142 docs(import): correct formatting of json examples for export and import
  docs/docs/guides/integrate/export-and-import.md
Labels: category: docs

#4119 docs: normalised versions and explained releases
  deploy/knative/zitadel-knative-service.yaml
  docs/docs/guides/deploy/docker-compose.yaml
  docs/docs/guides/deploy/knative.mdx
  docs/docs/guides/deploy/linux.mdx
  docs/docs/guides/deploy/loadbalancing-example/docker-compose.yaml
  docs/docs/guides/deploy/macos.mdx
  docs/docs/guides/deploy/overview.mdx
  docs/docs/guides/manage/self-hosted/configure/docker-compose.yaml
Labels: category: docs

#4128 docs(trainings): onboarding project
  docs/docs/guides/trainings/introduction.md
  docs/docs/guides/trainings/project.md
  docs/sidebars.js
Labels: category: docs

#4155 chore(docs): add link to v1 docs
  docs/docusaurus.config.js
Labels: category: docs

#4161 chore: added multiple browser support
  .github/workflows/e2e.yml
Labels: category: infra

#4165 fix(IDP): correct org idp response resourceowner
  internal/api/grpc/idp/converter.go
Labels: type: bug, lang: go, category: backend

#4186 docs: update rate limiting docs
  docs/docs/apis/ratelimits/api.md
  docs/docs/apis/ratelimits/login.md
  docs/docs/apis/ratelimits/ratelimits.md
  docs/docs/legal/rate-limit-policy.md
  docs/docusaurus.config.js
  docs/sidebars.js
Labels: category: docs, type: fix

#4202 docs: fixing incomplete sentence and old aud scope
  docs/docs/examples/secure-api/go.md
Labels: category: docs

#4184 fix: instance interceptors return NotFound (404) error for unknown hosts
  internal/api/grpc/server/middleware/instance_interceptor.go
  internal/api/grpc/server/middleware/instance_interceptor_test.go
  internal/api/http/middleware/instance_interceptor.go
  internal/api/http/middleware/instance_interceptor_test.go
  internal/api/ui/console/console.go
  internal/query/instance.go
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/mock/storage_mock.go
Labels: category: backend

#4239 ci: delete environment.json
  console/src/assets/.gitignore
  console/src/assets/environment.json
Labels: category: ci

#4257 fix: action query
  internal/api/grpc/action/action.go
  internal/api/grpc/management/actions_converter.go
  internal/query/action.go
Labels: type: bug, lang: go, category: backend, priority: medium

#3729 docs(contributing): Update contributing guide
  .github/workflows/test-code.yml
  .goreleaser.yaml
  CONTRIBUTING.md
  console/package.json
  console/src/app/pages/home/home.component.html
  e2e/cypress.config.ts
  e2e/cypress/e2e/applications/applications.cy.ts
  e2e/cypress/e2e/humans/humans.cy.ts
  e2e/cypress/e2e/machines/machines.cy.ts
  e2e/cypress/e2e/permissions/permissions.cy.ts
  e2e/cypress/e2e/projects/projects.cy.ts
  e2e/cypress/e2e/settings/login-policy.cy.ts
  e2e/cypress/e2e/settings/password-complexity.cy.ts
  e2e/cypress/e2e/settings/private-labeling.cy.ts
  e2e/cypress/support/api/apiauth.ts
  e2e/cypress/support/login/users.ts
  e2e/cypress/tsconfig.json
  e2e/docker-compose.yaml
  e2e/package-lock.json
  e2e/package.json
  e2e/tsconfig.json
Labels: category: docs

#4268 fix(import): check exists
  internal/api/grpc/admin/import.go
  internal/command/instance_idp_config.go
  internal/command/project_grant_member.go
  internal/command/project_member.go
  internal/command/user_human_otp.go
  internal/command/user_idp_link.go
  internal/command/user_idp_link_test.go
  internal/eventstore/handler/crdb/handler_stmt_test.go
  internal/eventstore/handler/crdb/lock_test.go
  internal/user/repository/view/model/user.go
Labels: lang: go, category: backend, type: fix, state: in progress, effort: 2
