Repository zitadel/zitadel, pull requests merged in 2022-05, with the labels that each got.

#3645 feat: default to local development
  cmd/defaults.yaml
Labels: v2

#3647 ci: publish releases
  .github/workflows/zitadel.yml
  .goreleaser.yaml
  .releaserc.js
Labels: v2

#3646 docs: installation
  build/local/docker-compose-local.yml
  build/local/local.env
  deploy/compose/docker-compose.yaml
  docs/docs/guides/installation/checkup.md
  docs/docs/guides/installation/compose.mdx
  docs/docs/guides/installation/configuration.mdx
  docs/docs/guides/installation/crd.md
  docs/docs/guides/installation/gitops.md
  docs/docs/guides/installation/helm.mdx
  docs/docs/guides/installation/installation.mdx
  docs/docs/guides/installation/linux.mdx
  docs/docs/guides/installation/macos.mdx
  docs/docs/guides/installation/managed-dedicated-instance.md
  docs/docs/guides/installation/openlocal.mdx
  docs/docs/guides/installation/orbos.md
  docs/docs/guides/installation/setup-orbos.md
  docs/docs/guides/installation/setup.md
  docs/docs/guides/installation/shared-cloud.md
  docs/docs/guides/installation/templates/boom.yml
  docs/docs/guides/installation/templates/crd/database.yml
  docs/docs/guides/installation/templates/crd/zitadel.yml
  docs/docs/guides/installation/templates/gitops/database.yml
  docs/docs/guides/installation/templates/gitops/zitadel.yml
  docs/docs/guides/installation/windows.mdx
  docs/sidebars.js
Labels: documentation, enhancement

#3649 chore: improve docker-compose.yml
  deploy/compose/docker-compose.yml
  docs/docs/guides/installation/linux.mdx
  docs/docs/guides/installation/macos.mdx
Labels: v2

#3670 docs: clearer masterkey, configure iam admin
  deploy/compose/docker-compose.yml
  docs/docs/guides/installation/compose.mdx
  docs/docs/guides/installation/configuration.mdx
  docs/docs/guides/installation/linux.mdx
  docs/docs/guides/installation/macos.mdx
  docs/docs/guides/installation/openlocal.mdx
Labels: documentation

#3679 fix: "EMail" typo
  internal/api/ui/login/static/i18n/de.yaml
Labels: enhancement

#3699 docs: Update trainings, footer, and emails
  docs/docs/guides/trainings/application.md
  docs/docs/guides/trainings/introduction.md
  docs/docs/guides/trainings/recurring.md
  docs/docs/guides/trainings/supportservice/application.md
  docs/docs/guides/trainings/supportservice/operations.md
  docs/docs/legal/privacy-policy.md
  docs/docs/legal/support-services.md
  docs/docusaurus.config.js
  docs/sidebars.js
  docs/static/img/training_support_services.png
Labels: documentation

#3626 feat: Configurable Unique Machine Identification
  cmd/admin/initialise/config.go
  cmd/admin/initialise/init.go
  cmd/admin/initialise/verify_zitadel.go
  cmd/admin/start/start.go
  cmd/defaults.yaml
  go.mod
  go.sum
  guides/development.md
  guides/production.md
  internal/auth/repository/eventsourcing/repository.go
  internal/authz/repository/eventsourcing/repository.go
  internal/command/command.go
  internal/command/instance.go
  internal/command/org.go
  internal/command/project_application_api.go
  internal/command/project_application_api_test.go
  internal/command/project_application_oidc.go
  internal/command/project_application_oidc_test.go
  internal/eventstore/handler/crdb/handler_stmt_test.go
  internal/eventstore/handler/crdb/lock.go
  internal/eventstore/v1/spooler/config.go
  internal/id/config.go
  internal/id/sonyflake.go
  internal/repository/project/api_config.go
  internal/repository/project/oidc_config.go
Labels: enhancement, go, v2
