Repository zitadel/zitadel, pull requests merged in 2022-12, with the labels that each got.

#4777 fix(query): add tracing for each method
  internal/query/action.go
  internal/query/action_flow.go
  internal/query/app.go
  internal/query/authn_key.go
  internal/query/certificate.go
  internal/query/changes.go
  internal/query/current_sequence.go
  internal/query/custom_text.go
  internal/query/domain_policy.go
  internal/query/iam_member.go
  internal/query/idp.go
  internal/query/idp_login_policy_link.go
  internal/query/idp_user_link.go
  internal/query/instance.go
  internal/query/instance_domain.go
  internal/query/key.go
  internal/query/label_policy.go
  internal/query/lockout_policy.go
  internal/query/login_policy.go
  internal/query/mail_template.go
  internal/query/message_text.go
  internal/query/notification_provider.go
  internal/query/oidc_settings.go
  internal/query/org.go
  internal/query/org_domain.go
  internal/query/org_member.go
  internal/query/org_metadata.go
  internal/query/password_age_policy.go
  internal/query/password_complexity_policy.go
  internal/query/privacy_policy.go
  internal/query/project.go
  internal/query/project_grant.go
  internal/query/project_grant_member.go
  internal/query/project_member.go
  internal/query/project_role.go
  internal/query/secret_generators.go
  internal/query/sms.go
  internal/query/smtp.go
  internal/query/user.go
  internal/query/user_auth_method.go
  internal/query/user_grant.go
  internal/query/user_membership.go
  internal/query/user_metadata.go
  internal/query/user_otp.go
  internal/query/user_password.go
  internal/query/user_personal_access_token.go
  internal/query/zitadel_permission.go
Labels: type: enhancement, lang: go, category: backend, state: in progress

#4811 fix(projection): new version of oidc_settings
  internal/query/oidc_settings_test.go
  internal/query/projection/oidc_settings.go
  internal/query/projection/oidc_settings_test.go
Labels: type: bug, category: backend, priority: high, state: in progress, effort: 1

#4815 fix: correct where statement for AppByOIDCClientID
  internal/query/app.go
Labels: lang: go, category: backend, type: hotfix

#4817 fix: corrected statement to when an init code has to be sent
  internal/auth/repository/eventsourcing/handler/user.go
  internal/command/user_human.go
Labels: lang: go, category: backend, type: fix

#4856 fix(database): add `MaxIdleConns` configuration
  cmd/defaults.yaml
  internal/database/cockroach/config.go
  internal/database/postgres/config.go
Labels: lang: go, category: backend, priority: high, state: in progress, effort: 1

#4502 feat: Instance create
  cmd/defaults.yaml
  cmd/setup/03.go
  cmd/setup/config.go
  cmd/setup/steps.yaml
  cmd/start/config.go
  docs/docs/apis/proto/system.md
  internal/api/grpc/admin/import.go
  internal/api/grpc/admin/user_converter.go
  internal/api/grpc/management/user.go
  internal/api/grpc/management/user_converter.go
  internal/api/grpc/system/instance.go
  internal/api/grpc/system/instance_converter.go
  internal/api/ui/login/register_org_handler.go
  internal/command/instance.go
  internal/command/org.go
  internal/command/user.go
  internal/command/user_machine.go
  internal/command/user_machine_key.go
  internal/command/user_machine_key_test.go
  internal/command/user_machine_test.go
  internal/command/user_personal_access_token.go
  internal/command/user_personal_access_token_test.go
  internal/domain/application_key.go
  internal/domain/authn_key.go
  internal/domain/expiration.go
  internal/domain/machine_key.go
  proto/zitadel/system.proto
Labels: type: enhancement, lang: go, category: backend

#4875 fix: protect default and zitadel project org from remove
  internal/command/main_test.go
  internal/command/org.go
  internal/command/org_test.go
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/i18n/zh.yaml
Labels: lang: go, category: backend, priority: high

#4877 docs: setup with service account docs
  docs/docs/guides/deploy/compose.mdx
  docs/docs/guides/deploy/docker-compose-sa.yaml
  docs/docs/guides/deploy/kubernetes.mdx
  docs/docs/guides/deploy/linux.mdx
  docs/docs/guides/deploy/macos.mdx
Labels: category: docs

#4847 fix: change back to login button and add to register option screen
  console/src/app/modules/policies/login-texts/helper.ts
  docs/docs/apis/proto/text.md
  internal/api/grpc/text/custom_text.go
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/register_option.html
  internal/command/custom_login_text.go
  internal/command/custom_login_text_model.go
  internal/command/instance_custom_login_text_test.go
  internal/domain/custom_login_text.go
  proto/zitadel/text.proto
Labels: category: backend, category: frontend

#4904 fix: 1.87.x export user grants
  internal/api/grpc/admin/export.go
Labels: lang: go, category: backend, type: fix

#4848 fix: separate tos and privacy checkbox into two
  console/src/app/modules/policies/login-texts/helper.ts
  docs/docs/apis/proto/text.md
  internal/api/grpc/text/custom_text.go
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/external_not_found_option.html
  internal/api/ui/login/static/templates/external_register_overview.html
  internal/api/ui/login/static/templates/register.html
  internal/api/ui/login/static/templates/register_org.html
  internal/command/custom_login_text.go
  internal/command/custom_login_text_model.go
  internal/command/instance_custom_login_text_test.go
  internal/command/org_custom_login_text_test.go
  internal/domain/custom_login_text.go
  internal/query/custom_text.go
  proto/zitadel/text.proto
Labels: lang: go, category: backend, type: fix

#4917 feat: org remove on admin api and org query with state
  docs/docs/apis/proto/admin.md
  docs/docs/apis/proto/org.md
  internal/api/grpc/admin/org.go
  internal/api/grpc/org/converter.go
  internal/query/org.go
  proto/zitadel/admin.proto
  proto/zitadel/org.proto
Labels: lang: go, category: backend, type: feature

#4916 docs(self-hosting): add env vars for proxy configuration
  docs/docs/self-hosting/manage/configure/configure.mdx
Labels: category: docs, state: in progress, effort: 1

#4932 docs(self-hosting): describe updating and scaling
  docs/docs/self-hosting/manage/production.md
  docs/docs/self-hosting/manage/updating_scaling.md
  docs/sidebars.js
Labels: category: docs
