Repository zitadel/zitadel, pull requests merged in 2022-09, with the labels that each got.

#4290 fix: WebAuthN (registration / login) and list on users
  internal/admin/repository/eventsourcing/eventstore/administrator.go
  internal/query/projection/user_auth_method.go
  internal/query/projection/user_auth_method_test.go
  internal/query/user_auth_method_test.go
  internal/webauthn/webauthn.go
Labels: type: bug, lang: go, category: backend, priority: high

#4291 fix: initial failures
  cmd/initialise/verify_zitadel.go
  cmd/setup/config.go
  internal/database/cockroach/config.go
  internal/database/postgres/config.go
  internal/eventstore/handler/crdb/handler_stmt.go
  internal/eventstore/handler/crdb/statement.go
  internal/eventstore/handler/crdb/statement_test.go
  internal/query/projection/app_test.go
  internal/query/projection/authn_key_test.go
  internal/query/projection/login_name_test.go
  internal/query/projection/sms_test.go
  internal/query/projection/user_grant_test.go
  internal/query/projection/user_test.go
Labels: type: bug, lang: go, category: backend, type: hotfix, priority: high, state: in progress, effort: 1

#4207 fix(console, e2e): optimize console and activate tests
  .github/workflows/test-code.yml
  console/src/app/app.component.ts
  console/src/app/guards/role.guard.ts
  console/src/app/modules/org-table/org-table.component.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.html
  console/src/app/services/grpc-auth.service.ts
  e2e/cypress/e2e/humans/humans.cy.ts
  e2e/cypress/e2e/machines/machines.cy.ts
  e2e/cypress/e2e/permissions/permissions.cy.ts
  e2e/cypress/e2e/projects/projects.cy.ts
Labels: category: ci

#4300 fix: improve performance
  cmd/defaults.yaml
  cmd/setup/04.go
  cmd/setup/04/cockroach/index.sql
  cmd/setup/04/postgres/index.sql
  cmd/setup/config.go
  cmd/setup/setup.go
  internal/authz/repository/eventsourcing/eventstore/token_verifier.go
  internal/eventstore/handler/handler_projection.go
  internal/eventstore/repository/search_query.go
  internal/eventstore/repository/sql/crdb.go
  internal/eventstore/search_query.go
  internal/eventstore/search_query_test.go
Labels: lang: go, category: backend, priority: high

#4301 fix: postgreSQL version spec
  README.md
  cmd/initialise/verify_database.go
  cmd/initialise/verify_grant.go
  cmd/initialise/verify_user.go
  cmd/initialise/verify_zitadel.go
  docs/docs/concepts/architecture/software.md
  docs/docs/guides/manage/self-hosted/database/_postgres.mdx
Labels: category: docs, priority: low, type: fix, state: in progress, effort: 1

#4333 fix(cli): no more panics during startup
  cmd/initialise/config.go
  cmd/initialise/init.go
  cmd/initialise/verify_database.go
  cmd/initialise/verify_grant.go
  cmd/initialise/verify_user.go
  cmd/start/config.go
Labels: lang: go, category: backend, type: fix, state: in progress, effort: 1

#4336 docs(oidc): use correct audience (issuer) for JWT Profile
  docs/docs/apis/openidoauth/authn-methods.md
  docs/docs/apis/openidoauth/grant-types.md
  docs/docs/guides/integrate/serviceusers.md
Labels: category: docs

#4295 fix(assets): correct type column in assets
  internal/static/database/crdb.go
  internal/static/database/crdb_test.go
  internal/static/storage.go
Labels: type: bug, lang: go, category: backend, priority: high

#4222 feat: internationalization Chinese
  console/src/app/app.component.ts
  console/src/app/app.module.ts
  console/src/app/pages/users/user-detail/auth-user-detail/auth-user-detail.component.ts
  console/src/app/pipes/localized-date-pipe/localized-date.pipe.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/zh.json
  docs/docs/guides/manage/customize/texts.md
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/notification/static/i18n/zh.yaml
  internal/static/i18n/zh.yaml
Labels: category: backend, category: frontend, priority: medium, category: translation

#4339 docs: list path prefixes
  docs/docs/apis/introduction.mdx
Labels: category: docs, type: enhancement

#4343 docs: SAML Guide Atlassian and Gitlab
  docs/docs/guides/integrate/atlassian-saml.md
  docs/docs/guides/integrate/gitlab-saml.md
  docs/sidebars.js
  docs/static/img/saml/atlassian/atlassian-01.png
  docs/static/img/saml/atlassian/atlassian-02.png
  docs/static/img/saml/atlassian/atlassian-03.png
  docs/static/img/saml/atlassian/atlassian-04.png
  docs/static/img/saml/atlassian/atlassian-05.png
  docs/static/img/saml/atlassian/atlassian-06.png
  docs/static/img/saml/gitlab/gitlab-01.png
  docs/static/img/saml/gitlab/gitlab-02.png
  docs/static/img/saml/gitlab/gitlab-03.png
Labels: category: docs

#4328 docs(terraform): add basic terraform documentation
  docs/docs/guides/manage/terraform/basics.md
  docs/sidebars.js
Labels: category: docs, state: in progress

#4371 fix(auth): always get token by id and user id
  .gitignore
  internal/api/oidc/auth_request.go
  internal/api/oidc/client.go
  internal/auth/repository/eventsourcing/eventstore/token.go
  internal/auth/repository/eventsourcing/view/token.go
  internal/auth/repository/token.go
  internal/authz/repository/eventsourcing/eventstore/token_verifier.go
  internal/authz/repository/eventsourcing/view/token.go
  internal/user/repository/view/token_view.go
Labels: type: bug, lang: go, category: backend, state: ready, effort: 1

#4382 docs(nginx): change example for webauthn
  docs/docs/guides/manage/self-hosted/proxy/_nginx.mdx
Labels: category: docs, priority: low

#4372 docs(concepts): add self-service to features
  docs/docs/concepts/features/selfservice.md
  docs/sidebars.js
Labels: category: docs

#4442 ci(e2e): save interesting container logs
  .github/workflows/e2e.yml
  .github/workflows/test-code.yml
Labels: docker, npm, category: ci

#4440 feat(instance): add functionality to update instance
  docs/docs/apis/proto/system.md
  internal/api/grpc/system/instance.go
  internal/command/instance.go
  internal/command/instance_model.go
  internal/command/instance_test.go
  internal/command/user_domain_policy_test.go
  internal/command/user_password_complexity_policy_test.go
  internal/query/projection/instance.go
  internal/repository/instance/aggregate.go
  internal/repository/instance/instance.go
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/i18n/zh.yaml
  proto/zitadel/system.proto
Labels: lang: go, category: backend, type: feature

#4413 fix: correct oidcsettings management
  cmd/defaults.yaml
  console/angular.json
  console/src/app/modules/policies/oidc-configuration/oidc-configuration.component.html
  console/src/app/modules/policies/oidc-configuration/oidc-configuration.component.ts
  console/src/app/services/admin.service.ts
  docs/docs/apis/proto/admin.md
  e2e/cypress/e2e/settings/oidc-settings.cy.ts
  e2e/cypress/support/api/apiauth.ts
  e2e/cypress/support/api/ensure.ts
  e2e/cypress/support/api/oidc-settings.ts
  internal/api/grpc/admin/oidc_settings.go
  internal/api/grpc/admin/oidc_settings_converter.go
  internal/api/oidc/auth_request.go
  internal/api/oidc/client.go
  internal/command/instance.go
  internal/command/instance_oidc_settings.go
  internal/command/instance_oidc_settings_test.go
  internal/command/smtp.go
  internal/query/projection/oidc_settings.go
  internal/repository/instance/oidc_settings.go
  proto/zitadel/admin.proto
Labels: type: bug, lang: go, category: backend, priority: high
