Repository zitadel/zitadel, pull requests merged in 2022-03, with the labels that each got.

#3270 docs: fix $SID => $TWILIO_SID
  docs/docs/guides/installation/crd.md
  docs/docs/guides/installation/gitops.md
Labels: bug, documentation, operator

#3333 fix: ensure backward compatibility with version 1.82.2
  cmd/zitadel/setup.yaml
  cmd/zitadel/startup.yaml
  operator/database/kinds/backups/bucket/backup/adapt.go
  operator/database/kinds/backups/bucket/restore/adapt.go
  operator/database/kinds/backups/s3/backup/adapt.go
  operator/database/kinds/backups/s3/backup/job.go
  operator/database/kinds/backups/s3/restore/adapt.go
  operator/database/kinds/backups/s3/restore/job.go
  operator/database/kinds/databases/managed/adapt.go
  operator/database/kinds/databases/managed/current/current.go
  operator/database/kinds/databases/managed/user/adapt.go
  operator/database/kinds/databases/managed/user/dbuser/adapt.go
  operator/database/kinds/databases/managed/user/node/adapt.go
  operator/zitadel/kinds/dbconn/cockroachdb/adapt.go
  operator/zitadel/kinds/dbconn/cockroachdb/current.go
  operator/zitadel/kinds/dbconn/cockroachdb/desired.go
  operator/zitadel/kinds/dbconn/cockroachdb/secrets.go
  operator/zitadel/kinds/iam/zitadel/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/adapt.go
  operator/zitadel/kinds/iam/zitadel/configuration/desired.go
  operator/zitadel/kinds/iam/zitadel/configuration/literals.go
  operator/zitadel/kinds/iam/zitadel/deployment/adapt.go
  operator/zitadel/kinds/iam/zitadel/deployment/container.go
  operator/zitadel/kinds/iam/zitadel/migration/adapt.go
  operator/zitadel/kinds/iam/zitadel/migration/migrationcontainer.go
  operator/zitadel/kinds/iam/zitadel/migration/precontainer.go
  operator/zitadel/kinds/iam/zitadel/setup/adapt.go
  operator/zitadel/kinds/iam/zitadel/users.go
  pkg/databases/certs/certificates/certificates.go
  pkg/databases/certs/certificates/certificates_test.go
  pkg/databases/certs/client/adapt.go
  pkg/databases/certs/client/adapt_test.go
  pkg/databases/certs/client/query.go
  pkg/databases/certs/client/query_test.go
  pkg/databases/certs/pem/pem.go
  pkg/databases/connection.go
  pkg/databases/db/client.go
Labels: bug, operator

#3347 docs: fix initial zitadel admin name
  guides/quickstart.md
Labels: bug, documentation

#3346 fix: don't use CR_USER variable
  build/local/docker-compose-local.yml
  build/local/e2e-setup-overwrite.env
  build/local/local.env
  operator/zitadel/kinds/iam/zitadel/configuration/literals.go
Labels: bug

#3247 docs: edits to guide section
  docs/docs/apis/proto/management.md
  docs/docs/concepts/structure/_granted_project_description.mdx
  docs/docs/concepts/structure/_org_description.mdx
  docs/docs/concepts/structure/_project_description.mdx
  docs/docs/guides/api/access-zitadel-apis.md
  docs/docs/guides/authentication/authmethods/basic.mdx
  docs/docs/guides/authentication/authmethods/implicit.mdx
  docs/docs/guides/authentication/authmethods/jwtpk.mdx
  docs/docs/guides/authentication/authmethods/pkce.mdx
  docs/docs/guides/authentication/authmethods/pkcenative.mdx
  docs/docs/guides/authentication/identity-brokering.md
  docs/docs/guides/authentication/login-users.mdx
  docs/docs/guides/authentication/serviceusers.md
  docs/docs/guides/authorization/oauth-recommended-flows.md
  docs/docs/guides/basics/get-started.mdx
  docs/docs/guides/basics/organizations.mdx
  docs/docs/guides/basics/projects.md
  docs/docs/guides/customization/branding.md
  docs/docs/guides/customization/texts.md
  docs/docs/guides/integrations/authenticated-mongodb-charts.md
  docs/docs/guides/overview.mdx
  docs/docs/guides/solution-scenarios/b2b.mdx
  docs/docs/guides/solution-scenarios/b2c.mdx
  docs/docs/guides/solution-scenarios/introduction.mdx
  docs/docs/guides/trainings/introduction.md
  docs/docs/guides/trainings/supportservice/application.md
  docs/docs/guides/trainings/supportservice/operations.md
  docs/docs/guides/trainings/supportservice/recurring.md
  docs/docs/manuals/introduction.mdx
  docs/docs/manuals/user-factors.md
  docs/docs/manuals/user-passwordless.md
  docs/docs/manuals/user-register.md
  docs/docs/manuals/user-social-login.md
  docs/docs/quickstarts/identity-proxy/oauth2-proxy.md
  docs/docs/quickstarts/login/nextjs.md
Labels: documentation

#3311 docs: fixes to quickstart language
  docs/docs/apis/introduction.mdx
  docs/docs/apis/openidoauth/endpoints.md
  docs/docs/apis/openidoauth/scopes.md
  docs/docs/apis/proto/admin.md
  docs/docs/apis/proto/auth.md
  docs/docs/apis/statuscodes.mdx
  docs/docs/concepts/architecture.md
  docs/docs/concepts/introduction.mdx
  docs/docs/concepts/structure/_granted_project_description.mdx
  docs/docs/concepts/structure/users.md
  docs/docs/guides/api/access-zitadel-apis.md
  docs/docs/guides/authentication/identity-brokering.md
  docs/docs/manuals/user-factors.md
  docs/docs/quickstarts/call-zitadel-api/dot-net.md
  docs/docs/quickstarts/call-zitadel-api/go.md
  docs/docs/quickstarts/identity-proxy/oauth2-proxy.md
  docs/docs/quickstarts/introduction.mdx
  docs/docs/quickstarts/libs.md
  docs/docs/quickstarts/login/angular.md
  docs/docs/quickstarts/login/flutter.md
  docs/docs/quickstarts/login/nextjs.md
  docs/docs/quickstarts/login/react.md
  docs/docs/quickstarts/secure-api/go.md
Labels: documentation

#3388 feat: ensure google cloud run compatibility
  .gitignore
  build/Dockerfile
  go.mod
  internal/id/sonyflake.go
Labels: enhancement, go, backend, infra
