Repository zitadel/zitadel, pull requests merged in 2023-02, with the labels that each got.

#5150 feat(api): allow specifying access_token type (opaque/JWT) for service users
  docs/docs/apis/proto/management.md
  docs/docs/apis/proto/user.md
  go.mod
  go.sum
  internal/api/grpc/management/user_converter.go
  internal/api/grpc/user/converter.go
  internal/api/oidc/client.go
  internal/api/oidc/client_credentials.go
  internal/api/oidc/jwt-profile.go
  internal/command/org_member_test.go
  internal/command/org_test.go
  internal/command/user_machine.go
  internal/command/user_machine_key_test.go
  internal/command/user_machine_model.go
  internal/command/user_machine_secret_test.go
  internal/command/user_machine_test.go
  internal/command/user_personal_access_token_test.go
  internal/command/user_test.go
  internal/domain/token.go
  internal/query/iam_member_test.go
  internal/query/org_member_test.go
  internal/query/project_grant_member_test.go
  internal/query/project_member_test.go
  internal/query/projection/user.go
  internal/query/projection/user_test.go
  internal/query/user.go
  internal/query/user_grant_test.go
  internal/query/user_test.go
  internal/repository/user/machine.go
  proto/zitadel/management.proto
  proto/zitadel/user.proto
Labels: lang: go, category: backend, type: feature

#5220 feat: add management for ldap idp template
  docs/docs/apis/proto/admin.md
  docs/docs/apis/proto/idp.md
  docs/docs/apis/proto/management.md
  go.mod
  go.sum
  internal/api/grpc/admin/idp.go
  internal/api/grpc/admin/idp_converter.go
  internal/api/grpc/idp/converter.go
  internal/api/grpc/management/idp.go
  internal/api/grpc/management/idp_converter.go
  internal/command/idp.go
  internal/command/idp_model.go
  internal/command/instance_idp.go
  internal/command/instance_idp_model.go
  internal/command/instance_idp_test.go
  internal/command/org_idp.go
  internal/command/org_idp_model.go
  internal/command/org_idp_test.go
  internal/domain/idp.go
  internal/idp/providers/ldap/ldap.go
  internal/idp/providers/ldap/ldap_test.go
  internal/idp/providers/ldap/session.go
  internal/idp/providers/ldap/user.go
  internal/query/idp_template.go
  internal/query/idp_template_test.go
  internal/query/projection/idp_template.go
  internal/query/projection/idp_template_test.go
  internal/query/projection/projection.go
  internal/repository/idp/idp.go
  internal/repository/idp/ldap.go
  internal/repository/instance/eventstore.go
  internal/repository/instance/idp.go
  internal/repository/org/eventstore.go
  internal/repository/org/idp.go
  proto/zitadel/admin.proto
  proto/zitadel/idp.proto
  proto/zitadel/management.proto
Labels: lang: go, category: backend, type: feature

#5022 docs: change image tag for docker compose with service account
  docs/docs/self-hosting/deploy/docker-compose-sa.yaml
Labels: category: docs

#4926 fix: don't close stdout
  cmd/setup/03.go
Labels: lang: go, category: backend, type: fix

#4902 docs(helm): remove crdb values
  docs/docs/self-hosting/deploy/kubernetes.mdx
Labels: category: docs

#5268 fix: update saml dependency to v0.0.10
  go.mod
  go.sum
Labels: lang: go, category: backend, type: fix
