Repository zitadel/zitadel, pull requests merged in 2023-03, with the labels that each got.

#5404 fix: add authURLParams to urls for external idps
  internal/api/ui/login/external_provider_handler.go
  internal/idp/providers/jwt/jwt.go
  internal/idp/providers/oauth/oauth2.go
  internal/idp/providers/oidc/oidc.go
Labels: lang: go, category: backend, type: fix

#5447 docs(legal): support services editorial changes
  docs/docs/legal/support-services.md
Labels: category: docs

#5504 docs(metrics): fix typos
  docs/docs/apis/observability/metrics.md
Labels: category: docs

#5448 feat: ldap provider login
  go.mod
  go.sum
  internal/api/grpc/admin/idp_converter.go
  internal/api/grpc/idp/converter.go
  internal/api/grpc/management/idp_converter.go
  internal/api/ui/login/external_provider_handler.go
  internal/api/ui/login/ldap_handler.go
  internal/api/ui/login/renderer.go
  internal/api/ui/login/router.go
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/pl.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/ldap_login.html
  internal/auth/repository/auth_request.go
  internal/auth/repository/eventsourcing/eventstore/auth_request.go
  internal/command/idp.go
  internal/command/idp_model.go
  internal/command/instance_idp.go
  internal/command/instance_idp_model.go
  internal/command/instance_idp_test.go
  internal/command/org_idp.go
  internal/command/org_idp_model.go
  internal/command/org_idp_test.go
  internal/idp/providers/ldap/ldap.go
  internal/idp/providers/ldap/ldap_test.go
  internal/idp/providers/ldap/session.go
  internal/idp/providers/ldap/session_test.go
  internal/query/idp_template.go
  internal/query/idp_template_test.go
  internal/query/projection/idp_template.go
  internal/query/projection/idp_template_test.go
  internal/repository/idp/ldap.go
  internal/repository/instance/idp.go
  internal/repository/org/idp.go
  proto/zitadel/admin.proto
  proto/zitadel/idp.proto
  proto/zitadel/management.proto
Labels: lang: go, category: backend, category: frontend, type: feature

#5535 fix: correct conditions for user update after actions in post authent…
  internal/api/ui/login/custom_action.go
  internal/api/ui/login/external_provider_handler.go
  internal/api/ui/login/jwt_handler.go
  internal/api/ui/login/ldap_handler.go
Labels: lang: go, category: backend, type: fix

#5445 feat: add Help/Support e-mail for instance/org
  cmd/defaults.yaml
  console/src/app/modules/policies/login-texts/helper.ts
  console/src/app/modules/policies/privacy-policy/privacy-policy.component.html
  console/src/app/modules/policies/privacy-policy/privacy-policy.component.scss
  console/src/app/modules/policies/privacy-policy/privacy-policy.component.ts
  console/src/app/modules/settings-list/settings-list.component.html
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/zh.json
  docs/docs/guides/manage/console/instance-settings.mdx
  docs/static/img/guides/console/privacypolicy.png
  internal/api/grpc/admin/export.go
  internal/api/grpc/admin/privacy_policy_converter.go
  internal/api/grpc/management/policy_privacy_converter.go
  internal/api/grpc/policy/privacy_policy.go
  internal/api/grpc/text/custom_text.go
  internal/api/ui/login/renderer.go
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/pl.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/footer.html
  internal/auth/repository/eventsourcing/eventstore/auth_request.go
  internal/command/custom_login_text.go
  internal/command/custom_login_text_model.go
  internal/command/instance.go
  internal/command/instance_converter.go
  internal/command/instance_custom_login_text.go
  internal/command/instance_custom_login_text_test.go
  internal/command/instance_policy_privacy.go
  internal/command/instance_policy_privacy_model.go
  internal/command/instance_policy_privacy_test.go
  internal/command/org_converter.go
  internal/command/org_custom_login_text_test.go
  internal/command/org_policy_privacy.go
  internal/command/org_policy_privacy_model.go
  internal/command/org_policy_privacy_test.go
  internal/command/policy_privacy_model.go
  internal/domain/custom_login_text.go
  internal/domain/policy_privacy.go
  internal/iam/model/privacy_policy_view.go
  internal/query/custom_text.go
  internal/query/privacy_policy.go
  internal/query/privacy_policy_test.go
  internal/query/projection/privacy_policy.go
  internal/query/projection/privacy_policy_test.go
  internal/repository/instance/policy_privacy.go
  internal/repository/org/policy_privacy.go
  internal/repository/policy/policy_privacy.go
  proto/zitadel/admin.proto
  proto/zitadel/management.proto
  proto/zitadel/policy.proto
  proto/zitadel/text.proto
Labels: state: waiting

#5360 fix: remove hardcoded texts
  console/src/app/modules/policies/private-labeling-policy/private-labeling-policy.component.html
  console/src/assets/i18n/de.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/zh.json
Labels: state: waiting
