Repository zitadel/zitadel, pull requests merged in 2023-04, with the labels that each got.

#5628 fix: update saml to v0.0.11
  cmd/start/start.go
  go.mod
  go.sum
  internal/api/oidc/op.go
  internal/api/saml/provider.go
Labels: lang: go, category: backend, type: fix

#5625 docs(migrate): Migrate to ZITADEL
  docs/docs/guides/migrate/introduction.md
  docs/docs/guides/migrate/sources/auth0.md
  docs/docs/guides/migrate/sources/zitadel-v1.md
  docs/docs/guides/migrate/users.md
  docs/sidebars.js
Labels: category: docs

#5605 fix(console): set options, idp layout
  console/src/app/modules/providers/provider-azure-ad/provider-azure-ad.component.html
  console/src/app/modules/providers/provider-azure-ad/provider-azure-ad.component.ts
  console/src/app/modules/providers/provider-github-es/provider-github-es.component.html
  console/src/app/modules/providers/provider-github-es/provider-github-es.component.ts
  console/src/app/modules/providers/provider-github/provider-github.component.html
  console/src/app/modules/providers/provider-gitlab-self-hosted/provider-gitlab-self-hosted.component.html
  console/src/app/modules/providers/provider-gitlab/provider-gitlab.component.html
  console/src/app/modules/providers/provider-google/provider-google.component.html
  console/src/app/modules/providers/provider-ldap/provider-ldap.component.html
  console/src/app/modules/providers/provider-oauth/provider-oauth.component.html
  console/src/app/modules/providers/provider-oauth/provider-oauth.component.ts
  console/src/app/modules/providers/provider-oidc/provider-oidc.component.ts
  console/src/app/modules/providers/providers.scss
  console/src/app/services/admin.service.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/zh.json
Labels: category: frontend
