Repository zitadel/zitadel, pull requests merged in 2023-06, with the labels that each got.

#5956 docs(troubleshoot): invalid audience
  docs/docs/support/troubleshooting.md
Labels: docs

#5980 fix: check linked users before postAuthentication action
  internal/api/ui/login/external_provider_handler.go
Labels: lang: go, backend, fix

#6003 fix: check if application is active in saml logic
  internal/api/saml/storage.go
Labels: fix
