Repository zitadel/zitadel, pull requests merged in 2023-01, with the labels that each got.

#4930 fix: correct display name when adding an instance
  .golangci.yaml
  internal/api/grpc/system/instance_converter.go
Labels: lang: go, category: backend, type: hotfix

#4931 test(e2e): improve error reporting
  console/src/app/services/toast.service.ts
  e2e/cypress/e2e/applications/applications.cy.ts
  e2e/cypress/e2e/humans/humans.cy.ts
  e2e/cypress/e2e/machines/machines.cy.ts
  e2e/cypress/e2e/organization/organizations.cy.ts
  e2e/cypress/e2e/permissions/permissions.cy.ts
  e2e/cypress/e2e/projects/projects.cy.ts
  e2e/cypress/e2e/settings/oidc-settings.cy.ts
  e2e/cypress/support/commands.ts
  e2e/cypress/support/login/users.ts
  e2e/package-lock.json
  e2e/package.json
Labels: lang: javascript

#4977 docs: describe linting in the dev process
  CONTRIBUTING.md
Labels: category: docs

#4989 feat(admin-api): list events
  CONTRIBUTING.md
  build/zitadel/Dockerfile
  build/zitadel/generate-grpc.sh
  cmd/defaults.yaml
  deploy/knative/cockroachdb-statefulset-single-node.yaml
  docs/docs/apis/proto/admin.md
  docs/docs/apis/proto/event.md
  docs/docs/self-hosting/deploy/docker-compose-sa.yaml
  docs/docs/self-hosting/deploy/docker-compose.yaml
  docs/docs/self-hosting/deploy/linux.mdx
  docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml
  docs/docs/self-hosting/deploy/macos.mdx
  docs/docs/self-hosting/manage/configure/docker-compose.yaml
  e2e/docker-compose.yaml
  internal/api/grpc/admin/event.go
  internal/eventstore/eventstore.go
  internal/eventstore/eventstore_test.go
  internal/eventstore/example_test.go
  internal/eventstore/search_query.go
  internal/migration/command.go
  internal/query/event.go
  internal/repository/action/eventstore.go
  internal/repository/instance/eventstore.go
  internal/repository/keypair/eventstore.go
  internal/repository/org/eventstore.go
  internal/repository/project/eventstore.go
  internal/repository/user/eventstore.go
  internal/repository/usergrant/eventstore.go
  proto/zitadel/admin.proto
  proto/zitadel/event.proto
Labels: lang: go, category: backend

#5013 feat: add listIamMembers to system api
  docs/docs/apis/proto/system.md
  internal/api/grpc/system/instance.go
  internal/api/grpc/system/instance_converter.go
  proto/zitadel/system.proto
Labels: lang: go, category: backend, type: feature

#5103 feat: add http request to interal and external authentication actions
  docs/docs/apis/actions/external-authentication.md
  docs/docs/apis/actions/internal-authentication.md
  docs/docs/apis/actions/objects.md
  internal/actions/object/auth_request.go
  internal/actions/object/http_request.go
  internal/api/ui/login/custom_action.go
  internal/api/ui/login/external_login_handler.go
  internal/api/ui/login/external_register_handler.go
  internal/api/ui/login/jwt_handler.go
  internal/api/ui/login/mfa_verify_handler.go
  internal/api/ui/login/mfa_verify_u2f_handler.go
  internal/api/ui/login/password_handler.go
  internal/api/ui/login/passwordless_login_handler.go
  internal/api/ui/login/register_handler.go
Labels: category: docs, lang: go, category: backend, type: feature

#5134 feat: support client_credentials for service users
  console/src/app/pages/users/user-detail/user-detail.module.ts
  console/src/app/pages/users/user-detail/user-detail/machine-secret-dialog/machine-secret-dialog.component.html
  console/src/app/pages/users/user-detail/user-detail/machine-secret-dialog/machine-secret-dialog.component.scss
  console/src/app/pages/users/user-detail/user-detail/machine-secret-dialog/machine-secret-dialog.component.spec.ts
  console/src/app/pages/users/user-detail/user-detail/machine-secret-dialog/machine-secret-dialog.component.ts
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.html
  console/src/app/pages/users/user-detail/user-detail/user-detail.component.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/zh.json
  docs/docs/apis/openidoauth/endpoints.mdx
  docs/docs/apis/openidoauth/grant-types.md
  docs/docs/apis/proto/management.md
  docs/docs/apis/proto/user.md
  docs/docs/guides/integrate/client-credentials.md
  docs/sidebars.js
  docs/static/img/console_serviceusers_secret.gif
  go.mod
  go.sum
  internal/api/grpc/management/user.go
  internal/api/grpc/user/converter.go
  internal/api/oidc/client.go
  internal/api/oidc/client_credentials.go
  internal/command/user_machine_model.go
  internal/command/user_machine_secret.go
  internal/command/user_machine_secret_test.go
  internal/domain/machine_secret.go
  internal/query/iam_member_test.go
  internal/query/org_member_test.go
  internal/query/project_grant_member_test.go
  internal/query/project_member_test.go
  internal/query/projection/user.go
  internal/query/projection/user_test.go
  internal/query/user.go
  internal/query/user_grant_test.go
  internal/query/user_test.go
  internal/repository/user/eventstore.go
  internal/repository/user/machine_secret.go
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/i18n/zh.yaml
  proto/zitadel/management.proto
  proto/zitadel/user.proto
Labels: lang: go, category: backend, type: feature
