Repository zitadel/zitadel, pull requests merged in 2024-06, with the labels that each got.

#8090 fix: read correct defaults
  cmd/mirror/mirror.go
Labels: lang: go, backend

#8045 feat(init): configurable existing postgres db
  cmd/defaults.yaml
  internal/database/cockroach/crdb.go
  internal/database/postgres/pg.go
Labels: improvement, storage

#8098 docs: typo in oauth2-proxy.md
  docs/docs/examples/identity-proxy/oauth2-proxy.md
Labels: os-contribution

#8101 fix(login): ldap login page js file not found
  internal/api/ui/login/static/templates/ldap_login.html
Labels: os-contribution

#8124 fix(v2): correct eventstore query
  internal/v2/eventstore/postgres/query.go
  internal/v2/eventstore/postgres/query_test.go
Labels: storage

#8105 feat: Contribute i18n swedish language
  console/src/app/app.module.ts
  console/src/app/utils/language.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
  docs/docs/guides/manage/customize/texts.md
  internal/api/ui/login/static/i18n/bg.yaml
  internal/api/ui/login/static/i18n/cs.yaml
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/es.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/ja.yaml
  internal/api/ui/login/static/i18n/mk.yaml
  internal/api/ui/login/static/i18n/nl.yaml
  internal/api/ui/login/static/i18n/pl.yaml
  internal/api/ui/login/static/i18n/pt.yaml
  internal/api/ui/login/static/i18n/ru.yaml
  internal/api/ui/login/static/i18n/sv.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/external_not_found_option.html
  internal/notification/static/i18n/sv.yaml
  internal/static/i18n/sv.yaml
Labels: os-contribution

#8141 fix: mdc dialog styles not being applied to secret generator module
  console/src/app/modules/policies/secret-generator/secret-generator.module.ts
Labels: os-contribution

#8144 fix: show "Default settings" for small screens < 600px
  console/src/app/modules/header/header.component.scss
Labels: os-contribution

#8147 fix(8076): last name chip on text messages
  console/src/app/modules/policies/message-texts/message-texts.component.ts
Labels: os-contribution

#8131 fix: pat token overflow in dialog
  console/src/app/modules/show-token-dialog/show-token-dialog.component.html
  console/src/app/modules/show-token-dialog/show-token-dialog.component.scss
Labels: os-contribution

#8095 docs: add developing with dev containers
  .devcontainer/docker-compose.yml
  CONTRIBUTING.md
  docs/docs/self-hosting/deploy/devcontainer.mdx
  docs/sidebars.js
Labels: docs

#8036 chore(docs): Migrate from Docusaurus v2 to v3
  docs/docs/apis/openidoauth/claims.md
  docs/docs/apis/openidoauth/endpoints.mdx
  docs/docs/apis/v3.mdx
  docs/docs/concepts/features/audit-trail.md
  docs/docs/concepts/features/external-user-grant.md
  docs/docs/concepts/features/identity-brokering.md
  docs/docs/concepts/structure/applications.md
  docs/docs/concepts/structure/users.md
  docs/docs/examples/identity-proxy/oauth2-proxy.md
  docs/docs/examples/login/angular.md
  docs/docs/examples/login/go.md
  docs/docs/examples/login/java-spring.md
  docs/docs/examples/login/nextjs-b2b.md
  docs/docs/examples/login/nextjs.md
  docs/docs/examples/login/symfony.md
  docs/docs/guides/integrate/identity-providers/introduction.md
  docs/docs/guides/integrate/identity-providers/keycloak.mdx
  docs/docs/guides/integrate/identity-providers/linkedin_oauth.mdx
  docs/docs/guides/integrate/identity-providers/mocksaml.mdx
  docs/docs/guides/integrate/identity-providers/okta-oidc.mdx
  docs/docs/guides/integrate/identity-providers/okta_saml.mdx
  docs/docs/guides/integrate/onboarding/b2b.mdx
  docs/docs/guides/integrate/retrieve-user-roles.md
  docs/docs/guides/integrate/service-users/authenticate-service-users.md
  docs/docs/guides/integrate/service-users/client-credentials.md
  docs/docs/guides/integrate/services/atlassian-saml.md
  docs/docs/guides/integrate/services/auth0-saml.md
  docs/docs/guides/integrate/services/aws-saml.md
  docs/docs/guides/integrate/services/cloudflare-oidc.mdx
  docs/docs/guides/integrate/services/gitlab-saml.md
  docs/docs/guides/integrate/services/google-workspace.md
  docs/docs/guides/integrate/tools/apache2.mdx
  docs/docs/guides/manage/console/default-settings.mdx
  docs/docs/guides/manage/console/projects.mdx
  docs/docs/guides/manage/customize/restrictions.md
  docs/docs/guides/manage/customize/user-metadata.md
  docs/docs/guides/migrate/users.md
  docs/docs/legal/policies/privacy-policy.mdx
  docs/docs/self-hosting/deploy/compose.mdx
  docs/docs/self-hosting/deploy/loadbalancing-example/loadbalancing-example.mdx
  docs/docs/self-hosting/manage/configure/_compose.mdx
  docs/docs/self-hosting/manage/configure/_helm.mdx
  docs/docs/self-hosting/manage/configure/_linuxunix.mdx
  docs/docs/self-hosting/manage/database/database.mdx
  docs/docs/self-hosting/manage/reverseproxy/httpd/httpd.mdx
  docs/docs/self-hosting/manage/reverseproxy/nginx/nginx.mdx
  docs/docs/self-hosting/manage/reverseproxy/traefik/traefik.mdx
  docs/docs/self-hosting/manage/usage_control.md
  docs/docusaurus.config.js
  docs/package.json
  docs/sidebars.js
  docs/vercel.json
  docs/yarn.lock
  proto/zitadel/admin.proto
  proto/zitadel/auth.proto
  proto/zitadel/system.proto
Labels: os-contribution

#7968 feat: send test mail
  console/src/app/modules/smtp-provider/smtp-provider.component.html
  console/src/app/modules/smtp-provider/smtp-provider.component.ts
  console/src/app/modules/smtp-provider/smtp-provider.scss
  console/src/app/modules/smtp-table/smtp-table.component.html
  console/src/app/modules/smtp-table/smtp-table.component.ts
  console/src/app/modules/smtp-table/smtp-table.module.ts
  console/src/app/modules/smtp-test-dialog/smtp-test-dialog.component.html
  console/src/app/modules/smtp-test-dialog/smtp-test-dialog.component.scss
  console/src/app/modules/smtp-test-dialog/smtp-test-dialog.component.spec.ts
  console/src/app/modules/smtp-test-dialog/smtp-test-dialog.component.ts
  console/src/app/modules/smtp-test-dialog/smtp-test-dialog.module.ts
  console/src/app/services/admin.service.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
  docs/docs/guides/manage/console/default-settings.mdx
  docs/static/img/guides/console/smtp_table.png
  docs/static/img/guides/console/smtp_test.png
  e2e/cypress/e2e/instance/settings/notifications.cy.ts
  internal/api/grpc/admin/smtp.go
  internal/command/smtp.go
  internal/command/smtp_test.go
  internal/notification/channels/smtp/channel.go
  internal/static/i18n/bg.yaml
  internal/static/i18n/cs.yaml
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/es.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/i18n/ja.yaml
  internal/static/i18n/mk.yaml
  internal/static/i18n/nl.yaml
  internal/static/i18n/pl.yaml
  internal/static/i18n/pt.yaml
  internal/static/i18n/ru.yaml
  internal/static/i18n/sv.yaml
  internal/static/i18n/zh.yaml
  proto/zitadel/admin.proto
Labels: os-contribution

#8175 chore(doc): do not expose database to public networks in examples
  docs/docs/self-hosting/deploy/docker-compose-sa.yaml
  docs/docs/self-hosting/deploy/docker-compose.yaml
  docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml
  docs/docs/self-hosting/manage/configure/docker-compose.yaml
  docs/docs/self-hosting/manage/reverseproxy/docker-compose.yaml
Labels: os-contribution

#8192 fix(console): minor UI issues
  console/src/app/modules/form-field/field/form-field.component.scss
  console/src/app/modules/policies/login-policy/factor-table/dialog-add-type/dialog-add-type.component.html
Labels: os-contribution

#8193 fix: RFC1342 encode sender name that goes in from header
  internal/notification/messages/email.go
Labels: os-contribution

#8180 fix(console): filters on user's list ignored if you go back from user details
  console/src/app/modules/filter-events/filter-events.component.html
  console/src/app/modules/filter/filter.component.html
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
Labels: os-contribution
