Repository zitadel/zitadel, pull requests merged in 2024-02, with the labels that each got.

#7360 fix: db MaxOpenConns setting
  internal/database/cockroach/crdb.go
  internal/database/postgres/pg.go
Labels: os-contribution

#7334 fix: trim whitespaces in redirect, post and origins uris set through console
  internal/command/project_application_oidc.go
  internal/command/project_application_oidc_test.go
  internal/domain/application_oidc.go
Labels: os-contribution

#7366 fix(console): change console favicon
  console/src/app/app.component.ts
  console/src/app/modules/policies/private-labeling-policy/private-labeling-policy.component.ts
  console/src/index.html
Labels: os-contribution

#7374 docs: Update retrieve-user-roles.md
  docs/docs/guides/integrate/retrieve-user-roles.md
Labels: os-contribution

#7335 fix(console): height fit-content for 2FA buttons
  console/src/app/pages/users/user-detail/auth-user-detail/auth-factor-dialog/auth-factor-dialog.component.scss
Labels: frontend, os-contribution

#7398 docs: Prevent console access
  docs/docs/concepts/structure/projects.md
  docs/docs/guides/manage/console/instance-settings.mdx
  docs/docs/guides/manage/console/overview.mdx
  docs/docs/guides/solution-scenarios/restrict-console.mdx
  docs/sidebars.js
  docs/static/img/guides/solution-scenarios/console-access-restricted.png
  docs/static/img/guides/solution-scenarios/console-check-project-auth.png
  docs/static/img/guides/solution-scenarios/console-create-project-grant-org.png
  docs/static/img/guides/solution-scenarios/console-default-project.png
  docs/static/img/guides/solution-scenarios/console-default-redirect.png
  docs/static/img/guides/solution-scenarios/console-zitadel-project-grants.png
Labels: docs, auth, resources

#6621 fix(backend): respect start flags in all commands
  cmd/start/flags.go
  go.mod
Labels: os-contribution

#7438 docs(integrate): fix typo in logout page
  docs/docs/guides/integrate/logout.md
Labels: os-contribution

#7429 fix: remove hard requirement of grant type auth code for device code apps + warnings for missing urls
  console/src/app/pages/projects/apps/app-create/app-create.component.html
  console/src/app/pages/projects/apps/app-detail/app-detail.component.ts
  console/src/app/pages/projects/apps/authmethods.ts
  internal/domain/application_oidc.go
  internal/domain/application_oidc_test.go
Labels: os-contribution
