Repository zitadel/zitadel, pull requests merged in 2024-11, with the labels that each got.

#8889 docs(v2): fix duplicate section of user, session, oidc and settings services
  docs/docusaurus.config.js
Labels: os-contribution

#8707 fix: fix slice init length
  internal/api/grpc/admin/export.go
Labels: os-contribution

#8852 fix(mirror): Fix instance_id check for tables without
  cmd/mirror/verify.go
Labels: os-contribution

#8907 fix: use correct check for user existing on import
  internal/command/user_human.go
Labels: os-contribution

#8894 docs: init benchmarks
  docs/docs/apis/benchmarks/_template.mdx
  docs/docs/apis/benchmarks/index.mdx
  docs/docs/apis/benchmarks/v2.65.0/machine_jwt_profile_grant/index.mdx
  docs/docs/apis/benchmarks/v2.65.0/machine_jwt_profile_grant/output.json
  docs/package.json
  docs/sidebars.js
  docs/src/components/benchmark_chart.jsx
  docs/static/img/benchmark/Flowchart.svg
  docs/yarn.lock
Labels: docs, storage

#8913 docs(user): change some deprecated links
  docs/docs/guides/manage/user/reg-create-user.md
  proto/zitadel/management.proto
Labels: os-contribution

#8923 fix: typo in defaults.yaml where ExternalPort should be ExternalDomain
  cmd/defaults.yaml
Labels: os-contribution

#8945 feat(eventstore): accept transaction in push
  internal/command/instance_debug_notification_log_test.go
  internal/database/database.go
  internal/eventstore/eventstore.go
  internal/eventstore/eventstore_bench_test.go
  internal/eventstore/eventstore_pusher_test.go
  internal/eventstore/eventstore_test.go
  internal/eventstore/repository/mock/repository.mock.go
  internal/eventstore/repository/mock/repository.mock.impl.go
  internal/eventstore/v3/eventstore.go
  internal/eventstore/v3/field.go
  internal/eventstore/v3/push.go
  internal/eventstore/v3/sequence.go
  internal/eventstore/v3/unique_constraints.go
Labels: storage

#8938 fix(console): bug fixes for ListProjectRoles and general pagination
  console/src/app/modules/paginator/paginator.component.html
  console/src/app/modules/paginator/paginator.component.ts
  console/src/app/modules/project-role-detail-dialog/project-role-detail-dialog.component.ts
  console/src/app/modules/project-roles-table/project-roles-table.component.html
  console/src/app/modules/project-roles-table/project-roles-table.component.ts
Labels: os-contribution

#8978 docs(adopter): RawkodeAcademy
  ADOPTERS.md
Labels: os-contribution
