Repository zitadel/zitadel, pull requests merged in 2024-03, with the labels that each got.

#7511 feat(i18n-cs): czech translation improvements
  console/src/assets/i18n/cs.json
  internal/api/ui/login/static/i18n/cs.yaml
Labels: os-contribution

#7383 fix: combine resourceowner query in reduce function for user grant
  internal/query/projection/instance_member_test.go
  internal/query/projection/org_member_test.go
  internal/query/projection/project_grant_member.go
  internal/query/projection/project_grant_member_test.go
  internal/query/projection/project_member_test.go
  internal/query/projection/user_grant.go
  internal/query/projection/user_grant_test.go
Labels: waiting

#7382 fix: add additional permission tests to user v2 query endpoints
  internal/api/grpc/user/v2/query.go
  internal/api/grpc/user/v2/query_integration_test.go
  internal/api/grpc/user/v2/user_integration_test.go
  internal/integration/integration.go
  internal/query/user.go
Labels: backend, fix, tests

#7497 fix: add expiration date information to service users keys
  console/src/app/modules/machine-keys/machine-keys.component.html
  console/src/app/modules/show-key-dialog/show-key-dialog.component.html
  console/src/app/modules/show-key-dialog/show-key-dialog.component.ts
  docs/docs/guides/integrate/private-key-jwt.md
  internal/command/user_machine_key.go
  internal/domain/machine_key.go
Labels: os-contribution

#7462 docs: onboarding users
  docs/docs/guides/integrate/onboarding/end-users.mdx
  docs/static/img/guides/solution-scenarios/register-options.png
Labels: docs

#7523 docs: Okta saml idp docs
  docs/docs/apis/actions/code-examples.mdx
  docs/docs/guides/integrate/identity-providers/_activate.mdx
  docs/docs/guides/integrate/identity-providers/_custom_login_policy.mdx
  docs/docs/guides/integrate/identity-providers/okta-oidc.mdx
  docs/docs/guides/integrate/identity-providers/okta_saml.mdx
  docs/docs/guides/integrate/login/login-users.mdx
  docs/sidebars.js
  docs/static/img/guides/okta_add_saml_app.png
  docs/static/img/guides/okta_assign_user_to_app.png
  docs/static/img/guides/okta_saml_attribute_mapping.png
  docs/static/img/guides/zitadel_activate_okta_saml.png
  docs/static/img/guides/zitadel_identity_provider_overview.png
  docs/static/img/guides/zitadel_okta_saml_provider_empty.png
  docs/static/img/guides/zitadel_okta_saml_provider_filled.png
Labels: docs

#7567 feat: updated russian translations by native speaker with a user poli…
  console/src/assets/i18n/ru.json
  internal/api/ui/login/static/i18n/ru.yaml
  internal/notification/static/i18n/ru.yaml
  internal/static/i18n/ru.yaml
Labels: os-contribution

#7562 docs: add org id header in missing requests
  proto/zitadel/management.proto
Labels: docs

#7492 docs(integrate): improve service user authentication
  docs/docs/apis/introduction.mdx
  docs/docs/concepts/features/audit-trail.md
  docs/docs/concepts/features/selfservice.md
  docs/docs/examples/secure-api/python-flask.mdx
  docs/docs/guides/integrate/access-zitadel-apis.md
  docs/docs/guides/integrate/client-credentials.md
  docs/docs/guides/integrate/external-audit-log.md
  docs/docs/guides/integrate/pat.md
  docs/docs/guides/integrate/private-key-jwt.md
  docs/docs/guides/integrate/retrieve-user-roles.md
  docs/docs/guides/integrate/service-users/authenticate-service-users.md
  docs/docs/guides/integrate/service-users/client-credentials.md
  docs/docs/guides/integrate/service-users/personal-access-token.md
  docs/docs/guides/integrate/service-users/private-key-jwt.md
  docs/docs/guides/integrate/token-introspection/index.md
  docs/docs/guides/integrate/token-introspection/private-key-jwt.mdx
  docs/docs/guides/integrate/zitadel-apis/_accessing_zitadel_api.md
  docs/docs/guides/integrate/zitadel-apis/access-zitadel-apis.md
  docs/docs/guides/integrate/zitadel-apis/access-zitadel-system-api.md
  docs/docs/guides/integrate/zitadel-apis/event-api.md
  docs/docs/guides/integrate/zitadel-apis/example-zitadel-api-with-dot-net.md
  docs/docs/guides/integrate/zitadel-apis/example-zitadel-api-with-go.md
  docs/docs/guides/manage/terraform/basics.md
  docs/docs/guides/migrate/sources/keycloak.md
  docs/docs/guides/migrate/sources/zitadel.md
  docs/docs/guides/solution-scenarios/restrict-console.mdx
  docs/docs/imports/_code-flow-chart.md
  docs/docs/self-hosting/manage/usage_control.md
  docs/docs/support/advisory/a10007.md
  docs/sidebars.js
  docs/static/img/console_service_user_tokentype.png
  docs/static/img/guides/integrate/service-users/sequence-private-key-jwt.svg
  docs/vercel.json
Labels: docs, auth

#7600 docs: add linkedin guide
  docs/docs/guides/integrate/identity-providers/_custom_login_policy.mdx
  docs/docs/guides/integrate/identity-providers/_generic_oauth.mdx
  docs/docs/guides/integrate/identity-providers/linkedin_oauth.mdx
  docs/sidebars.js
  docs/static/img/guides/linkedin_add_app.png
  docs/static/img/guides/linkedin_login.png
  docs/static/img/guides/zitadel_activate_linkedin.png
  docs/static/img/guides/zitadel_allow_external_idp.png
  docs/static/img/guides/zitadel_linkedin_create_provider.png
  docs/static/img/guides/zitadel_login_linkedin.png
Labels: docs

#7579 fix: Incorrect button positioning on email verification
  internal/api/ui/login/static/resources/themes/scss/styles/container/container.scss
  internal/api/ui/login/static/templates/mail_verified.html
Labels: frontend, os-contribution

#7626 fix: docs: keycloak user migration api error
  docs/docs/guides/migrate/sources/keycloak.md
Labels: os-contribution
