Repository zitadel/zitadel, pull requests merged in 2024-04, with the labels that each got.

#7677 docs(guides/integrate/service-users/private-key-jwt):
  docs/docs/guides/integrate/service-users/private-key-jwt.md
Labels: docs, os-contribution, auth

#7683 fix: Update url to redirect to name change url
  internal/api/ui/login/static/templates/register_option.html
Labels: os-contribution

#7692 docs: postgres healthcheck failing
  docs/docs/self-hosting/deploy/docker-compose.yaml
Labels: os-contribution, storage, devops

#7760 fix(setup): decode role mappings
  cmd/defaults.yaml
  cmd/setup/config.go
  cmd/start/config_test.go
Labels: bug, backend, reviewer wanted

#7803 chore: typo in api docs
  proto/zitadel/admin.proto
Labels: docs

#7829 test(e2e): fix events flakiness
  e2e/cypress/e2e/events/events.cy.ts
  internal/integration/config/zitadel.yaml
Labels: ci, reviewer wanted

#7671 feat: allow using a local RSA key for machine keys
  internal/api/grpc/management/user.go
  internal/api/grpc/management/user_converter.go
  internal/command/user_machine_key.go
  internal/command/user_machine_key_test.go
  internal/static/i18n/bg.yaml
  internal/static/i18n/cs.yaml
  internal/static/i18n/de.yaml
  internal/static/i18n/en.yaml
  internal/static/i18n/es.yaml
  internal/static/i18n/fr.yaml
  internal/static/i18n/it.yaml
  internal/static/i18n/ja.yaml
  internal/static/i18n/mk.yaml
  internal/static/i18n/nl.yaml
  internal/static/i18n/pl.yaml
  internal/static/i18n/pt.yaml
  internal/static/i18n/ru.yaml
  internal/static/i18n/zh.yaml
  proto/zitadel/management.proto
Labels: os-contribution

#7688 fix: weird issue with service key expirationDate format
  console/src/app/modules/machine-keys/machine-keys.component.html
  console/src/app/modules/paginator/paginator.component.html
  console/src/app/modules/personal-access-tokens/personal-access-tokens.component.html
  console/src/app/modules/show-key-dialog/show-key-dialog.component.html
Labels: frontend, os-contribution

#7781 fix(console): orgs list is shown empty when org is removed
  console/src/app/pages/orgs/org-detail/org-detail.component.ts
  console/src/app/services/admin.service.ts
  console/src/app/services/mgmt.service.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/zh.json
Labels: os-contribution

#7855 fix: remove email validation for SearchUsers v2beta/users
  proto/zitadel/member.proto
  proto/zitadel/user.proto
  proto/zitadel/user/v2beta/query.proto
  proto/zitadel/user/v3alpha/query.proto
Labels: os-contribution

#7844 fix(cnsl): Email Verified checkbox value was not updated
  console/src/app/pages/users/user-detail/auth-user-detail/edit-dialog/edit-dialog.component.html
Labels: os-contribution

#7848 fix: show settings button for users w/o iam perms
  console/src/app/modules/nav/nav.component.html
Labels: os-contribution
