Repository zitadel/zitadel, pull requests merged in 2024-09, with the labels that each got.

#8519 docs: typo fixes
  docs/docs/guides/integrate/onboarding/b2b.mdx
Labels: os-contribution

#8459 feat: add indonesia translation
  console/src/app/app.module.ts
  console/src/app/utils/language.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/id.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
  docs/docs/guides/manage/customize/texts.md
  internal/api/ui/login/static/i18n/bg.yaml
  internal/api/ui/login/static/i18n/cs.yaml
  internal/api/ui/login/static/i18n/de.yaml
  internal/api/ui/login/static/i18n/en.yaml
  internal/api/ui/login/static/i18n/es.yaml
  internal/api/ui/login/static/i18n/fr.yaml
  internal/api/ui/login/static/i18n/id.yaml
  internal/api/ui/login/static/i18n/it.yaml
  internal/api/ui/login/static/i18n/ja.yaml
  internal/api/ui/login/static/i18n/mk.yaml
  internal/api/ui/login/static/i18n/nl.yaml
  internal/api/ui/login/static/i18n/pl.yaml
  internal/api/ui/login/static/i18n/pt.yaml
  internal/api/ui/login/static/i18n/ru.yaml
  internal/api/ui/login/static/i18n/sv.yaml
  internal/api/ui/login/static/i18n/zh.yaml
  internal/api/ui/login/static/templates/external_not_found_option.html
  internal/notification/static/i18n/id.yaml
  internal/static/i18n/id.yaml
Labels: os-contribution

#8537 chore: automatically bump charts
  .github/workflows/release.yml
Labels: devops

#8496 fix(console): Verify if the LDAP IDP has just been created
  console/src/app/modules/providers/provider-ldap/provider-ldap.component.ts
Labels: os-contribution

#8551 docs: enterprise support for charts
  docs/docs/support/software-release-cycles-support.md
Labels: docs

#8527 fix(eventstore): precise decimal
  cmd/mirror/event.go
  cmd/mirror/event_store.go
  go.mod
  go.sum
  internal/api/oidc/key.go
  internal/api/saml/certificate.go
  internal/database/cockroach/crdb.go
  internal/database/postgres/pg.go
  internal/eventstore/event.go
  internal/eventstore/event_base.go
  internal/eventstore/eventstore.go
  internal/eventstore/eventstore_querier_test.go
  internal/eventstore/eventstore_test.go
  internal/eventstore/handler/v2/field_handler.go
  internal/eventstore/handler/v2/handler.go
  internal/eventstore/handler/v2/state.go
  internal/eventstore/handler/v2/state_test.go
  internal/eventstore/handler/v2/statement.go
  internal/eventstore/local_crdb_test.go
  internal/eventstore/read_model.go
  internal/eventstore/repository/event.go
  internal/eventstore/repository/mock/repository.mock.go
  internal/eventstore/repository/mock/repository.mock.impl.go
  internal/eventstore/repository/search_query.go
  internal/eventstore/repository/sql/crdb.go
  internal/eventstore/repository/sql/crdb_test.go
  internal/eventstore/repository/sql/query.go
  internal/eventstore/repository/sql/query_test.go
  internal/eventstore/search_query.go
  internal/eventstore/search_query_test.go
  internal/eventstore/v1/models/event.go
  internal/eventstore/v3/event.go
  internal/query/access_token.go
  internal/query/current_state.go
  internal/query/current_state_test.go
  internal/query/user_grant.go
  internal/query/user_membership.go
  internal/v2/database/number_filter.go
  internal/v2/eventstore/event_store.go
  internal/v2/eventstore/postgres/push_test.go
  internal/v2/eventstore/postgres/query_test.go
  internal/v2/eventstore/query.go
  internal/v2/eventstore/query_test.go
  internal/v2/readmodel/last_successful_mirror.go
  internal/v2/system/mirror/succeeded.go
  load-test/Makefile
  load-test/src/use_cases/manipulate_user.ts
Labels: storage

#8592 docs: some English spelling and grammar fixes
  console/src/assets/i18n/en.json
  internal/api/ui/login/static/i18n/en.yaml
Labels: os-contribution

#8495 feat(console): Display seconds and milliseconds in the tooltip of the user audit log
  console/src/app/modules/changes/changes.component.html
Labels: os-contribution

#8466 docs: upstream sent too big header while reading response header from upstream
  docs/docs/self-hosting/deploy/troubleshooting/_upstream_header.mdx
  docs/docs/self-hosting/deploy/troubleshooting/troubleshooting.mdx
Labels: os-contribution

#8681 docs(guides): Fixing incorrect placement of hyphen in overview
  docs/docs/guides/overview.mdx
Labels: os-contribution
