Repository zitadel/zitadel, pull requests merged in 2024-07, with the labels that each got.

#7869 fix: remove non-existent colums in getMembershipFromQuery queries
  internal/query/user_membership.go
Labels: os-contribution

#8240 fix: Fixed spelling and grammar misstakes
  internal/api/ui/login/static/i18n/de.yaml
Labels: os-contribution

#8163 feat: add expiry and domain chip to sms and email otp
  console/src/app/modules/policies/message-texts/message-texts.component.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
Labels: os-contribution

#8238 feat(console): add tooltip for indicator on inherit button in feature settings
  console/src/app/components/features/features.component.html
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
Labels: os-contribution

#8229 docs(cmd): document that human and service user can be used in the default instance
  cmd/defaults.yaml
  cmd/setup/steps.yaml
Labels: docs

#8252 docs: note audience scope for service user
  docs/docs/guides/integrate/service-users/client-credentials.md
  docs/docs/guides/integrate/service-users/private-key-jwt.md
Labels: os-contribution

#8088 test: add load test for session creation
  load-test/Makefile
  load-test/README.md
  load-test/src/oidc.ts
  load-test/src/session.ts
  load-test/src/use_cases/machine_client_credentials_login.ts
  load-test/src/use_cases/session.ts
  load-test/src/user.ts
Labels: backend, tests, performance

#8299 fix: Correct misspelling in zh.yaml file
  internal/api/ui/login/static/i18n/zh.yaml
Labels: os-contribution

#8293 fix(console): missing styles for ProfilePictureComponent dialog
  console/src/app/pages/users/user-detail/detail-form/detail-form.module.ts
Labels: os-contribution

#8294 feat(console): note about function names must match in action dialog
  console/src/app/pages/actions/add-action-dialog/add-action-dialog.component.html
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
Labels: os-contribution

#8265 feat: allow machine user id to be set during creation
  internal/api/grpc/management/user_converter.go
  internal/api/grpc/management/user_integration_test.go
  internal/command/user_machine_test.go
  proto/zitadel/management.proto
Labels: os-contribution

#8246 chore(lint): print error locations
  .github/workflows/lint.yml
Labels: devops

#8307 feat(console): replace secret generator dialogs with cards
  console/src/app/modules/policies/secret-generator/dialog-add-secret-generator/dialog-add-secret-generator.component.ts
  console/src/app/modules/policies/secret-generator/secret-generator-card/secret-generator-card.component.html
  console/src/app/modules/policies/secret-generator/secret-generator-card/secret-generator-card.component.scss
  console/src/app/modules/policies/secret-generator/secret-generator-card/secret-generator-card.component.ts
  console/src/app/modules/policies/secret-generator/secret-generator.component.html
  console/src/app/modules/policies/secret-generator/secret-generator.component.scss
  console/src/app/modules/policies/secret-generator/secret-generator.component.ts
  console/src/app/modules/policies/secret-generator/secret-generator.module.ts
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
  docs/static/img/guides/console/secretappearance.png
  e2e/cypress/e2e/instance/settings/secret-generator.cy.ts
Labels: os-contribution

#8327 fix: update IDP Success and Failure URLs to accept up to 2048 characters
  proto/zitadel/user/v2beta/idp.proto
  proto/zitadel/user/v3alpha/authenticator.proto
Labels: os-contribution

#8328 fix: always use pgxpool config if MaxOpenConns isn't set
  internal/database/cockroach/crdb.go
  internal/database/postgres/pg.go
Labels: os-contribution

#8232 docs(migrate): update password section
  cmd/defaults.yaml
  docs/docs/guides/migrate/users.md
Labels: waiting

#8321 feat: add delete phone endpoint to v2 api
  internal/api/grpc/user/v2/phone.go
  internal/api/grpc/user/v2/phone_integration_test.go
  internal/command/user_v2_phone.go
  internal/integration/client.go
  proto/zitadel/user/v2beta/user_service.proto
Labels: waiting, os-contribution

#8359 fix: Fixed more spelling and grammar misstakes
  console/src/assets/i18n/de.json
  internal/notification/static/i18n/de.yaml
Labels: os-contribution
