Repository zitadel/zitadel, pull requests merged in 2024-05, with the labels that each got.

#7854 fix(setup): decode complex config strings
  cmd/setup/config.go
  cmd/setup/config_test.go
  cmd/start/config.go
Labels: bug, backend

#7946 fix: typo in the fr translation file for login ui sms otp mfa
  internal/api/ui/login/static/i18n/fr.yaml
Labels: os-contribution

#7910 fix: Update fr translations
  console/src/assets/i18n/fr.json
  internal/api/ui/login/static/i18n/fr.yaml
  internal/notification/static/i18n/fr.yaml
  internal/static/i18n/fr.yaml
Labels: os-contribution

#7906 docs(go.md): HTTP example URL
  docs/docs/examples/secure-api/go.md
Labels: os-contribution

#7956 feat(console): add new step to activate SMTP provider
  console/src/app/modules/smtp-provider/smtp-provider.component.html
  console/src/app/modules/smtp-provider/smtp-provider.component.ts
  console/src/app/modules/smtp-provider/smtp-provider.scss
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/zh.json
  e2e/cypress/e2e/instance/settings/notifications.cy.ts
  e2e/cypress/e2e/organization/organizations.cy.ts
  internal/api/grpc/admin/iam_settings_converter.go
Labels: os-contribution

#8005 chore(cloud): increase rate limits
  docs/docs/legal/policies/rate-limit-policy.md
Labels: infra, cloud, devops

#8011 fix: Service User Description in English localization
  console/src/assets/i18n/en.json
Labels: os-contribution

#8018 docs(features): clean up audit trail feature
  docs/docs/concepts/features/audit-trail.md
Labels: docs

#7990 docs(service users): improve client id and client secret docs
  docs/docs/guides/integrate/service-users/client-credentials.md
Labels: docs
