Repository zitadel/zitadel, pull requests merged in 2025-01, with the labels that each got.

#9052 fix(listUsers): Add Search User By Phone to User Service V2
  internal/api/grpc/admin/integration_test/iam_member_test.go
  internal/api/grpc/management/integration_test/org_test.go
  internal/api/grpc/user/v2/integration_test/email_test.go
  internal/api/grpc/user/v2/integration_test/idp_link_test.go
  internal/api/grpc/user/v2/integration_test/phone_test.go
  internal/api/grpc/user/v2/integration_test/query_test.go
  internal/api/grpc/user/v2/query.go
  internal/api/grpc/user/v2beta/integration_test/email_test.go
  internal/api/grpc/user/v2beta/integration_test/phone_test.go
  internal/api/grpc/user/v2beta/integration_test/query_test.go
  internal/api/grpc/user/v2beta/query.go
  internal/integration/client.go
  proto/zitadel/user/v2/query.proto
  proto/zitadel/user/v2beta/query.proto
Labels: waiting, os-contribution

#9021 docs(adopters):Dribdat
  ADOPTERS.md
Labels: os-contribution, marketing

#9117 docs: change scope for zitadel audience
  docs/docs/guides/integrate/zitadel-apis/example-zitadel-api-with-dot-net.md
Labels: docs

#9146 perf(fields): create index for instance domain query
  cmd/setup/43.go
  cmd/setup/43/cockroach/43.sql
  cmd/setup/43/postgres/43.sql
  cmd/setup/config.go
  cmd/setup/setup.go
Labels: performance, storage

#9100 fix(i18n): typo in Russian login description
  internal/api/ui/login/static/i18n/ru.yaml
Labels: os-contribution

#9092 perf(eventstore): optimize commands to events function
  cmd/setup/40.go
  cmd/setup/40/postgres/02_func.sql
Labels: performance, storage

#9142 perf(eventstore): redefine current sequences index
  cmd/setup/44.go
  cmd/setup/44/01_create_index.sql
  cmd/setup/44/02_drop_old_index.sql
  cmd/setup/config.go
  cmd/setup/setup.go
Labels: performance, storage

#9132 feat: create user scim v2 endpoint
  cmd/defaults.yaml
  cmd/start/config.go
  cmd/start/start.go
  internal/api/http/header.go
  internal/api/http/middleware/auth_interceptor.go
  internal/api/http/middleware/handler.go
  internal/api/http/middleware/instance_interceptor.go
  internal/api/http/middleware/instance_interceptor_test.go
  internal/api/scim/authz.go
  internal/api/scim/config/config.go
  internal/api/scim/integration_test/scim_test.go
  internal/api/scim/integration_test/testdata/users_create_test_full.json
  internal/api/scim/integration_test/testdata/users_create_test_invalid_locale.json
  internal/api/scim/integration_test/testdata/users_create_test_invalid_password.json
  internal/api/scim/integration_test/testdata/users_create_test_invalid_profile_url.json
  internal/api/scim/integration_test/testdata/users_create_test_invalid_timezone.json
  internal/api/scim/integration_test/testdata/users_create_test_minimal.json
  internal/api/scim/integration_test/testdata/users_create_test_missing_email.json
  internal/api/scim/integration_test/testdata/users_create_test_missing_name.json
  internal/api/scim/integration_test/testdata/users_create_test_missing_username.json
  internal/api/scim/integration_test/users_create_test.go
  internal/api/scim/metadata/context.go
  internal/api/scim/metadata/metadata.go
  internal/api/scim/middleware/content_type_middleware.go
  internal/api/scim/middleware/content_type_middleware_test.go
  internal/api/scim/middleware/scim_context_middleware.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/resources/user_metadata.go
  internal/api/scim/schemas/schemas.go
  internal/api/scim/schemas/string.go
  internal/api/scim/schemas/string_test.go
  internal/api/scim/schemas/url.go
  internal/api/scim/schemas/url_test.go
  internal/api/scim/serrors/errors.go
  internal/api/scim/serrors/errors_test.go
  internal/api/scim/server.go
  internal/integration/assert.go
  internal/integration/client.go
  internal/integration/scim/client.go
  internal/zerrors/zerror.go
  internal/zerrors/zerror_test.go
Labels: os-contribution

#9151 feat: delete user scim v2 endpoint
  internal/api/scim/authz.go
  internal/api/scim/integration_test/users_create_test.go
  internal/api/scim/integration_test/users_delete_test.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/server.go
  internal/integration/scim/assertions.go
  internal/integration/scim/client.go
Labels: os-contribution

#9058 docs: update external-login.mdx according to api spec
  docs/docs/guides/integrate/login-ui/external-login.mdx
Labels: os-contribution

#9161 feat: get user scim v2 endpoint
  internal/api/scim/authz.go
  internal/api/scim/integration_test/users_get_test.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/resources/user_metadata.go
  internal/api/scim/server.go
  internal/integration/assert.go
  internal/integration/assert_test.go
  internal/integration/scim/client.go
Labels: os-contribution

#9163 feat: replace user scim v2 endpoint
  internal/api/scim/authz.go
  internal/api/scim/integration_test/testdata/users_create_test_minimal_inactive.json
  internal/api/scim/integration_test/testdata/users_replace_test_full.json
  internal/api/scim/integration_test/testdata/users_replace_test_minimal.json
  internal/api/scim/integration_test/testdata/users_replace_test_minimal_with_external_id.json
  internal/api/scim/integration_test/users_create_test.go
  internal/api/scim/integration_test/users_delete_test.go
  internal/api/scim/integration_test/users_get_test.go
  internal/api/scim/integration_test/users_replace_test.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/resources/user_metadata.go
  internal/api/scim/server.go
  internal/command/user_human.go
  internal/command/user_model.go
  internal/command/user_v2_human.go
  internal/integration/assert.go
  internal/integration/scim/client.go
Labels: os-contribution

#9168 feat(/internal): Add User Resource Owner
  internal/api/grpc/member/converter.go
  internal/query/iam_member.go
  internal/query/iam_member_test.go
  internal/query/member.go
  internal/query/org_member.go
  internal/query/org_member_test.go
  internal/query/project_grant_member.go
  internal/query/project_grant_member_test.go
  internal/query/project_member.go
  internal/query/project_member_test.go
  proto/zitadel/member.proto
Labels: os-contribution

#9195 fix: include tzdata to validate timezones in scim
  internal/api/scim/resources/user_metadata.go
Labels: os-contribution

#9105 refactor: consolidate database pools
  cmd/defaults.yaml
  cmd/initialise/init.go
  cmd/initialise/verify_zitadel.go
  cmd/key/key.go
  cmd/mirror/auth.go
  cmd/mirror/event_store.go
  cmd/mirror/projections.go
  cmd/mirror/system.go
  cmd/mirror/verify.go
  cmd/setup/cleanup.go
  cmd/setup/setup.go
  cmd/start/start.go
  internal/database/cockroach/crdb.go
  internal/database/database.go
  internal/database/dialect/config.go
  internal/database/dialect/config_test.go
  internal/database/dialect/connections.go
  internal/database/dialect/connections_test.go
  internal/database/postgres/pg.go
  internal/eventstore/repository/sql/query.go
  internal/eventstore/v3/push.go
Labels: backend, performance, storage

#9201 fix(eventstore): correct crdb sql push function
  cmd/setup/40.go
  cmd/setup/40/cockroach/40_init_push_func.sql
Labels: bug, storage

#9187 feat: list users scim v2 endpoint
  go.mod
  go.sum
  internal/api/http/parser.go
  internal/api/http/parser_test.go
  internal/api/scim/authz.go
  internal/api/scim/integration_test/users_create_test.go
  internal/api/scim/integration_test/users_get_test.go
  internal/api/scim/integration_test/users_list_test.go
  internal/api/scim/integration_test/users_replace_test.go
  internal/api/scim/resources/filter/filter_parser.go
  internal/api/scim/resources/filter/filter_parser_test.go
  internal/api/scim/resources/filter/filter_query_builder.go
  internal/api/scim/resources/filter/filter_query_builder_test.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/resource_list.go
  internal/api/scim/resources/resource_list_test.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/resources/user_metadata.go
  internal/api/scim/resources/user_query_builder.go
  internal/api/scim/resources/user_query_builder_test.go
  internal/api/scim/schemas/schemas.go
  internal/api/scim/serrors/errors.go
  internal/api/scim/server.go
  internal/integration/assert.go
  internal/integration/assert_test.go
  internal/integration/scim/client.go
  internal/query/prepare_test.go
  internal/query/search_query.go
  internal/query/search_query_test.go
  internal/query/user.go
  internal/query/user_metadata.go
  internal/query/user_metadata_test.go
  internal/query/user_test.go
  internal/test/assert.go
  internal/test/assert_test.go
Labels: os-contribution

#9226 fix: add aggregate type to subquery to utilize indexes
  internal/notification/handlers/notification_worker.go
Labels: os-contribution

#9244 fix: unified scim metadata key casing
  internal/api/scim/integration_test/users_create_test.go
  internal/api/scim/integration_test/users_get_test.go
  internal/api/scim/integration_test/users_list_test.go
  internal/api/scim/integration_test/users_replace_test.go
  internal/api/scim/metadata/metadata.go
Labels: os-contribution

#9245 fix: allow scim content type wildcards
  internal/api/scim/middleware/content_type_middleware.go
Labels: os-contribution

#9235 fix: scim user query endpoint don't allow SortBy custom field
  internal/api/scim/integration_test/users_list_test.go
  internal/api/scim/resources/resource_list.go
Labels: os-contribution

#9257 fix: scim 2 filter: the username should be treated case-insensitive
  internal/api/scim/resources/filter/filter_query_builder.go
  internal/api/scim/resources/filter/filter_query_builder_test.go
  internal/api/scim/resources/user_query_builder.go
  internal/query/search_query.go
  internal/query/search_query_test.go
Labels: os-contribution

#9256 feat: bulk scim v2 endpoint
  cmd/defaults.yaml
  internal/api/scim/authz.go
  internal/api/scim/config/config.go
  internal/api/scim/integration_test/bulk_test.go
  internal/api/scim/integration_test/scim_test.go
  internal/api/scim/integration_test/testdata/bulk_test_errors.json
  internal/api/scim/integration_test/testdata/bulk_test_fail_on_errors.json
  internal/api/scim/integration_test/testdata/bulk_test_full.json
  internal/api/scim/integration_test/users_list_test.go
  internal/api/scim/integration_test/users_update_test.go
  internal/api/scim/metadata/context.go
  internal/api/scim/middleware/scim_context_middleware.go
  internal/api/scim/resources/bulk.go
  internal/api/scim/resources/patch/patch.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/resource_list.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/schemas/schemas.go
  internal/api/scim/serrors/errors.go
  internal/api/scim/server.go
  internal/integration/scim/client.go
Labels: os-contribution

#9258 feat: add scim v2 service provider configuration endpoints
  cmd/defaults.yaml
  internal/api/scim/config/config.go
  internal/api/scim/integration_test/service_provider_config_test.go
  internal/api/scim/integration_test/testdata/service_provider_config_expected.json
  internal/api/scim/integration_test/testdata/service_provider_config_expected_resource_type_user.json
  internal/api/scim/integration_test/testdata/service_provider_config_expected_resource_types.json
  internal/api/scim/integration_test/testdata/service_provider_config_expected_schemas.json
  internal/api/scim/integration_test/testdata/service_provider_config_expected_user_schema.json
  internal/api/scim/resources/bulk.go
  internal/api/scim/resources/resource_handler.go
  internal/api/scim/resources/resource_handler_adapter.go
  internal/api/scim/resources/resource_list.go
  internal/api/scim/resources/user.go
  internal/api/scim/resources/user_mapping.go
  internal/api/scim/resources/user_query_builder.go
  internal/api/scim/schemas/schema_builder.go
  internal/api/scim/schemas/schemas.go
  internal/api/scim/schemas/string.go
  internal/api/scim/server.go
  internal/api/scim/service_provider.go
  internal/integration/scim/client.go
Labels: os-contribution

#9246 docs: scim v2 interface
  docs/docs/apis/scim2.md
  docs/docs/guides/manage/user/scim2.md
  docs/sidebars.js
Labels: os-contribution

#9282 fix: scim 2.0 patch ignore op casing
  internal/api/scim/integration_test/testdata/users_update_test_full.json
  internal/api/scim/resources/patch/patch.go
Labels: os-contribution

#9283 fix: scim create users dont send init emails
  internal/api/scim/resources/user.go
Labels: os-contribution
