Repository zitadel/zitadel, pull requests merged in 2025-04, with the labels that each got.

#9705 fix(console): correct count for users list, show create timestamp in user details
  console/src/app/modules/info-row/info-row.component.ts
  console/src/app/pages/users/user-list/user-table/user-table.component.ts
Labels: os-contribution

#9681 chore(i18n): add IAM_LOGIN_CLIENT
  console/src/assets/i18n/bg.json
  console/src/assets/i18n/cs.json
  console/src/assets/i18n/de.json
  console/src/assets/i18n/en.json
  console/src/assets/i18n/es.json
  console/src/assets/i18n/fr.json
  console/src/assets/i18n/hu.json
  console/src/assets/i18n/id.json
  console/src/assets/i18n/it.json
  console/src/assets/i18n/ja.json
  console/src/assets/i18n/ko.json
  console/src/assets/i18n/mk.json
  console/src/assets/i18n/nl.json
  console/src/assets/i18n/pl.json
  console/src/assets/i18n/pt.json
  console/src/assets/i18n/ro.json
  console/src/assets/i18n/ru.json
  console/src/assets/i18n/sv.json
  console/src/assets/i18n/zh.json
Labels: os-contribution

#9686 docs(adopters): Clean Energy Exchange AG
  ADOPTERS.md
Labels: os-contribution, marketing

#9804 docs: fix typo in Java SDK example document
  docs/docs/sdk-examples/java.mdx
Labels: os-contribution

#9802 fix: update link to postgres-insecure example in docs
  docs/docs/self-hosting/manage/configure/_helm.mdx
Labels: os-contribution

#9496 docs(self-hosting): add login to lb example
  docs/docs/self-hosting/deploy/loadbalancing-example/.gitignore
  docs/docs/self-hosting/deploy/loadbalancing-example/docker-compose.yaml
  docs/docs/self-hosting/deploy/loadbalancing-example/example-traefik.yaml
  docs/docs/self-hosting/deploy/loadbalancing-example/example-zitadel-config.yaml
  docs/docs/self-hosting/deploy/loadbalancing-example/example-zitadel-init-steps.yaml
  docs/docs/self-hosting/deploy/loadbalancing-example/loadbalancing-example.mdx
Labels: docs
