Repository zitadel/zitadel, pull requests merged in 2025-03, with the labels that each got.

#8529 docs: update oidc playground
  docs/docs/apis/introduction.mdx
  docs/docs/guides/integrate/identity-providers/_test_setup.mdx
  docs/docs/guides/integrate/login/login-users.mdx
  docs/docs/guides/integrate/login/oidc/authmethods/_basic.mdx
  docs/docs/guides/integrate/login/oidc/authmethods/_jwtpk.mdx
  docs/docs/guides/integrate/login/oidc/authmethods/_pkce.mdx
  docs/docs/guides/integrate/onboarding/end-users.mdx
  docs/docs/guides/manage/console/default-settings.mdx
  docs/docs/guides/manage/console/organizations.mdx
  docs/docs/guides/manage/customize/branding.md
  docs/docs/guides/manage/customize/user-metadata.md
  docs/docs/guides/migrate/introduction.md
  docs/docs/guides/solution-scenarios/domain-discovery.mdx
  docs/sidebars.js
  docs/src/components/authrequest.jsx
Labels: docs

#9441 docs: Clarify how to add the users' organization claim
  docs/docs/apis/openidoauth/scopes.md
Labels: os-contribution

#9459 fix(cmd): clarify notification config handling
  cmd/setup/setup.go
  cmd/start/start.go
  internal/queue/queue.go
Labels: reviewer wanted

#9537 docs: show proxy link only once
  docs/docs/self-hosting/manage/reverseproxy/_proxy_guide_overview.mdx
  docs/docs/self-hosting/manage/reverseproxy/_proxy_guide_tls_mode.mdx
  docs/docs/self-hosting/manage/reverseproxy/caddy/caddy.mdx
  docs/docs/self-hosting/manage/reverseproxy/httpd/httpd.mdx
  docs/docs/self-hosting/manage/reverseproxy/nginx/nginx.mdx
  docs/docs/self-hosting/manage/reverseproxy/traefik/traefik.mdx
Labels: docs

#9543 chore: Update contrib.rocks link in README.md
  README.md
Labels: os-contribution

#9542 chore: Replace deprecated `io/ioutil` functions with recommended alternatives
  internal/api/grpc/admin/import.go
  internal/command/project_application_saml_test.go
  internal/id/sonyflake.go
  internal/notification/templates/template.go
  internal/query/message_text.go
  internal/renderer/renderer.go
Labels: os-contribution

#9523 fix: reduce cardinality in metrics and tracing for unknown paths
  internal/api/grpc/server/gateway.go
Labels: os-contribution

#9493 feat(actions): Add refresh token to post authentication action context
  docs/docs/apis/actions/external-authentication.md
  internal/api/ui/login/custom_action.go
Labels: os-contribution

#9563 feat: Make service name configurable for Metrics and Tracing
  cmd/defaults.yaml
  internal/telemetry/metrics/otel/open_telemetry.go
  internal/telemetry/otel/resource.go
  internal/telemetry/tracing/google/google_tracer.go
  internal/telemetry/tracing/log/config.go
  internal/telemetry/tracing/otel/config.go
  internal/telemetry/tracing/otel/open_telemetry.go
Labels: os-contribution

#9596 feat(crypto): support md5 salted for imported password hashes
  cmd/defaults.yaml
  docs/docs/concepts/architecture/secrets.md
  go.mod
  go.sum
  internal/crypto/passwap.go
  internal/crypto/passwap_test.go
Labels: os-contribution

#9458 feat: add EXPOSE command to Dockerfile
  build/Dockerfile
Labels: waiting, os-contribution

#9561 feat: add prometheus metrics on projection handlers
  cmd/setup/config.go
  internal/eventstore/handler/v2/handler.go
  internal/eventstore/handler/v2/metrics.go
  internal/eventstore/handler/v2/metrics_test.go
  internal/telemetry/metrics/config/config.go
  internal/telemetry/metrics/metrics.go
  internal/telemetry/metrics/mock.go
  internal/telemetry/metrics/noop.go
  internal/telemetry/metrics/otel/open_telemetry.go
Labels: os-contribution

#9651 docs: invite user flow
  console/src/app/pages/users/user-create/user-create-v2/user-create-v2.component.html
  console/src/app/pages/users/user-create/user-create-v2/user-create-v2.component.scss
  console/src/app/pages/users/user-create/user-create-v2/user-create-v2.component.ts
  docs/docs/guides/manage/console/_create-user.mdx
  docs/static/img/guides/console/invitehuman.png
  docs/static/img/guides/console/setupauthmethod.png
Labels: docs
